"""
proper_of_time.py — Python port of romcal ProperOfTime.

AUTO-GENERATED by scripts/translate_proper_of_time.py. DO NOT EDIT BY HAND.
Re-run the script to regenerate after updating the romcal TypeScript source.

Supports both gregorian and liturgical scope:
  gregorian  — Advent/Christmas fall at yearOffset=+1 (end of civil year)
  liturgical — Advent starts the liturgical year (yearOffset=0)

After regenerating, validate with:
    pytest tests/test_proper_of_time_parity.py
"""
from __future__ import annotations

from romcal.models.calendar_def import CalendarDef
from romcal.models.liturgical_day_def import LiturgicalDayDef
from romcal.constants import PROPER_OF_TIME_NAME
from romcal.utils.objects import _Obj

# Weekday and month name arrays (match romcal WEEKDAYS / MONTHS constants)
WEEKDAYS = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday']
MONTHS   = ['january', 'february', 'march', 'april', 'may', 'june', 'july', 'august', 'september', 'october', 'november', 'december']


class ProperOfTime(CalendarDef):
    """
    Python port of romcal's ProperOfTime class.
    Generates all Proper of Time liturgical day definitions for a given scope.

    TS: ProperOfTime extends CalendarDef (src/proper-of-time/proper-of-time.ts)
    The constructor mirrors CalendarDef: ProperOfTime(config, inputs?).

    Usage:
        pot = ProperOfTime(config)
        pot.build_all_definitions(scope="gregorian")
        # definitions stored in config.liturgical_day_def
    """

    def __init__(self, config=None, inputs=None) -> None:
        super().__init__(config, inputs)
        self._weekdays: list[str] = WEEKDAYS
        self._months: list[str]   = MONTHS


    def build_all_definitions(self, scope: str = "gregorian") -> None:
        if self._definitions_built:
            return
        if scope == "gregorian":
            self.late_christmas_time()
            self.lent()
            self.paschal_triduum()
            self.easter_time()
            self.ordinary_time()
            self.advent(+1)
            self.early_christmas_time(+1)
        else:
            self.advent()
            self.christmas_time()
            self.lent()
            self.paschal_triduum()
            self.easter_time()
            self.ordinary_time()
        self._definitions_built = True

    def _new_def(self, id_, input_):
        return LiturgicalDayDef(id_, _Obj({"proper_cycle": "PROPER_OF_TIME", **input_}), PROPER_OF_TIME_NAME, self._config)

    def advent(self, year_offset=0):
        for i in range(20):
            week = int(i // 7) + 1
            dow = i - (week - 1) * 7
            self._new_def(f"advent_{week}_{self._weekdays[dow]}", _Obj({"precedence": ("PRIVILEGED_SUNDAY_2" if dow == 0 else "WEEKDAY_13"), "date_def": (_Obj({"date_fn": "sundayOfAdvent", "date_args": [week], "year_offset": -1 + year_offset}) if dow == 0 else _Obj({"date_fn": "unprivilegedWeekdayOfAdvent", "date_args": [dow, week], "year_offset": -1 + year_offset})), "is_holy_day_of_obligation": dow == 0, "seasons": ["ADVENT"], "periods": [], "calendar_metadata": _Obj({"week_of_season": week, "day_of_season": i + 1, "day_of_week": dow}), "colors": [*((["ROSE"] if week == 3 and dow == 0 else [])), "PURPLE"], "i18n_def": (["seasons:advent.sunday", _Obj({"week": week})] if dow == 0 else ["seasons:advent.weekday", _Obj({"week": week, "dow": dow})])}))
        self._new_def(f"advent_4_{self._weekdays[0]}", _Obj({"precedence": "PRIVILEGED_SUNDAY_2", "date_def": _Obj({"date_fn": "sundayOfAdvent", "date_args": [4], "year_offset": -1 + year_offset}), "is_holy_day_of_obligation": True, "seasons": ["ADVENT"], "periods": [], "calendar_metadata": _Obj({"week_of_season": 4, "day_of_season": 22, "day_of_week": 0}), "colors": ["PURPLE"], "i18n_def": ["seasons:advent.sunday", _Obj({"week": 4})]}))
        for day in range(17, 25):
            self._new_def(f"advent_{self._months[11]}_{day}", _Obj({"precedence": "PRIVILEGED_WEEKDAY_9", "date_def": _Obj({"date_fn": "privilegedWeekdayOfAdvent", "date_args": [day], "year_offset": -1 + year_offset}), "seasons": ["ADVENT"], "periods": [], "calendar_metadata": _Obj({}), "colors": ["PURPLE"], "i18n_def": ["seasons:advent.privileged_weekday", _Obj({"day": day})]}))

    def christmas_time(self, year_offset=0):
        self.early_christmas_time(year_offset)
        self.late_christmas_time(year_offset)

    def early_christmas_time(self, year_offset=0):
        self._new_def("nativity_of_the_lord", _Obj({"precedence": "PROPER_OF_TIME_SOLEMNITY_2", "date_def": _Obj({"date_fn": "christmas", "year_offset": -1 + year_offset}), "is_holy_day_of_obligation": True, "seasons": ["CHRISTMAS_TIME"], "periods": ["CHRISTMAS_OCTAVE", "CHRISTMAS_TO_PRESENTATION_OF_THE_LORD"], "calendar_metadata": _Obj({"week_of_season": 1, "day_of_season": 1}), "colors": ["WHITE"], "i18n_def": ["names:nativity_of_the_lord"]}))
        for count in range(2, 8):
            self._new_def(f"christmas_octave_day_{count}", _Obj({"precedence": "PRIVILEGED_WEEKDAY_9", "date_def": _Obj({"date_fn": "weekdayWithinOctaveOfChristmas", "date_args": [count], "year_offset": -1 + year_offset}), "seasons": ["CHRISTMAS_TIME"], "periods": ["CHRISTMAS_OCTAVE", "CHRISTMAS_TO_PRESENTATION_OF_THE_LORD"], "calendar_metadata": _Obj({"day_of_season": count}), "colors": ["WHITE"], "i18n_def": ["seasons:christmas_time.octave", _Obj({"count": count})]}))
        self._new_def("holy_family_of_jesus_mary_and_joseph", _Obj({"precedence": "GENERAL_LORD_FEAST_5", "date_def": _Obj({"date_fn": "holyFamily", "year_offset": -1 + year_offset}), "seasons": ["CHRISTMAS_TIME"], "periods": ["CHRISTMAS_OCTAVE", "CHRISTMAS_TO_PRESENTATION_OF_THE_LORD"], "calendar_metadata": _Obj({}), "colors": ["WHITE"], "i18n_def": ["names:holy_family_of_jesus_mary_and_joseph"]}))

    def late_christmas_time(self, year_offset=0):
        self._new_def("mary_mother_of_god", _Obj({"precedence": "GENERAL_SOLEMNITY_3", "date_def": _Obj({"date_fn": "maryMotherOfGod", "year_offset": year_offset}), "is_holy_day_of_obligation": True, "seasons": ["CHRISTMAS_TIME"], "periods": ["CHRISTMAS_OCTAVE", "CHRISTMAS_TO_PRESENTATION_OF_THE_LORD"], "calendar_metadata": _Obj({"day_of_season": 8}), "colors": ["WHITE"], "i18n_def": ["names:mary_mother_of_god"]}))
        self._new_def("second_sunday_after_christmas", _Obj({"precedence": "UNPRIVILEGED_SUNDAY_6", "date_def": _Obj({"date_fn": "secondSundayAfterChristmas", "year_offset": year_offset}), "is_holy_day_of_obligation": True, "seasons": ["CHRISTMAS_TIME"], "periods": ["CHRISTMAS_TO_PRESENTATION_OF_THE_LORD"], "calendar_metadata": _Obj({}), "colors": ["WHITE"], "i18n_def": ["seasons:christmas_time.second_sunday_after_christmas"]}))
        for day in range(2, 9):
            self._new_def(f"christmas_time_{self._months[0]}_{day}", _Obj({"precedence": "WEEKDAY_13", "date_def": _Obj({"date_fn": "weekdayBeforeEpiphany", "date_args": [day], "year_offset": year_offset}), "seasons": ["CHRISTMAS_TIME"], "periods": ["DAYS_BEFORE_EPIPHANY", "CHRISTMAS_TO_PRESENTATION_OF_THE_LORD"], "calendar_metadata": _Obj({"day_of_season": 7 + day}), "colors": ["WHITE"], "i18n_def": ["seasons:christmas_time.before_epiphany", _Obj({"day": day})]}))
        self._new_def("epiphany_of_the_lord", _Obj({"precedence": "PROPER_OF_TIME_SOLEMNITY_2", "date_def": _Obj({"date_fn": "epiphany", "year_offset": year_offset}), "is_holy_day_of_obligation": True, "seasons": ["CHRISTMAS_TIME"], "periods": ["DAYS_FROM_EPIPHANY", "CHRISTMAS_TO_PRESENTATION_OF_THE_LORD"], "calendar_metadata": _Obj({}), "colors": ["WHITE"], "i18n_def": ["names:epiphany_of_the_lord"]}))
        for dow in range(1, 7):
            self._new_def(f"{self._weekdays[dow]}_after_epiphany", _Obj({"precedence": "WEEKDAY_13", "date_def": _Obj({"date_fn": "weekdayAfterEpiphany", "date_args": [dow], "year_offset": year_offset}), "seasons": ["CHRISTMAS_TIME"], "periods": ["DAYS_FROM_EPIPHANY", "CHRISTMAS_TO_PRESENTATION_OF_THE_LORD"], "calendar_metadata": _Obj({}), "colors": ["WHITE"], "i18n_def": ["seasons:christmas_time.after_epiphany", _Obj({"dow": dow})]}))
        self._new_def("baptism_of_the_lord", _Obj({"precedence": "PROPER_OF_TIME_SOLEMNITY_2", "date_def": _Obj({"date_fn": "baptismOfTheLord", "year_offset": year_offset}), "seasons": ["CHRISTMAS_TIME"], "periods": ["DAYS_FROM_EPIPHANY", "CHRISTMAS_TO_PRESENTATION_OF_THE_LORD"], "calendar_metadata": _Obj({}), "colors": ["WHITE"], "i18n_def": ["names:baptism_of_the_lord"]}))

    def lent(self, year_offset=0):
        self._new_def("ash_wednesday", _Obj({"precedence": "ASH_WEDNESDAY_2", "date_def": _Obj({"date_fn": "ashWednesday", "year_offset": year_offset}), "seasons": ["LENT"], "periods": ["PRESENTATION_OF_THE_LORD_TO_HOLY_THURSDAY"], "calendar_metadata": _Obj({"week_of_season": 0, "day_of_season": 1, "day_of_week": 3}), "colors": ["PURPLE"], "i18n_def": ["names:ash_wednesday"]}))
        for dow in range(4, 7):
            self._new_def(f"{self._weekdays[dow]}_after_ash_wednesday", _Obj({"precedence": "PRIVILEGED_WEEKDAY_9", "date_def": _Obj({"date_fn": "ashWednesday", "add_day": dow - 3, "year_offset": year_offset}), "seasons": ["LENT"], "periods": ["PRESENTATION_OF_THE_LORD_TO_HOLY_THURSDAY"], "calendar_metadata": _Obj({"week_of_season": 0, "day_of_season": dow - 2, "day_of_week": dow}), "colors": ["PURPLE"], "i18n_def": ["seasons:lent.day_after_ash_wed", _Obj({"dow": dow})]}))
        for i in range(35):
            week = int(i // 7) + 1
            dow = i - (week - 1) * 7
            self._new_def(f"lent_{week}_{self._weekdays[dow]}", _Obj({"precedence": ("PRIVILEGED_SUNDAY_2" if dow == 0 else "PRIVILEGED_WEEKDAY_9"), "date_def": _Obj({"date_fn": "ashWednesday", "add_day": i + 4, "year_offset": year_offset}), "is_holy_day_of_obligation": dow == 0, "seasons": ["LENT"], "periods": ["PRESENTATION_OF_THE_LORD_TO_HOLY_THURSDAY"], "calendar_metadata": _Obj({"week_of_season": week, "day_of_season": i + 5, "day_of_week": dow}), "colors": [*((["ROSE"] if week == 4 and dow == 0 else [])), "PURPLE"], "i18n_def": (["seasons:lent.sunday", _Obj({"week": week})] if dow == 0 else ["seasons:lent.weekday", _Obj({"week": week, "dow": dow})])}))
        self._new_def("palm_sunday_of_the_passion_of_the_lord", _Obj({"precedence": "PRIVILEGED_SUNDAY_2", "date_def": _Obj({"date_fn": "palmSunday", "year_offset": year_offset}), "is_holy_day_of_obligation": True, "seasons": ["LENT"], "periods": ["HOLY_WEEK", "PRESENTATION_OF_THE_LORD_TO_HOLY_THURSDAY"], "calendar_metadata": _Obj({"week_of_season": 6, "day_of_season": 40, "day_of_week": 0}), "colors": ["RED"], "i18n_def": ["names:palm_sunday_of_the_passion_of_the_lord"]}))
        for dow in range(1, 5):
            self._new_def(f"holy_{self._weekdays[dow]}", _Obj({"precedence": "PRIVILEGED_WEEKDAY_9", "date_def": _Obj({"date_fn": "palmSunday", "add_day": dow, "year_offset": year_offset}), "seasons": ["LENT"], "periods": ["HOLY_WEEK", "PRESENTATION_OF_THE_LORD_TO_HOLY_THURSDAY"], "calendar_metadata": _Obj({"week_of_season": 6, "day_of_season": 40 + dow, "day_of_week": dow}), "colors": ["PURPLE"], "i18n_def": ["seasons:lent.holy_week_day", _Obj({"dow": dow})]}))

    def paschal_triduum(self, year_offset=0):
        self._new_def("thursday_of_the_lords_supper", _Obj({"precedence": "TRIDUUM_1", "date_def": _Obj({"date_fn": "holyThursday", "year_offset": year_offset}), "seasons": ["PASCHAL_TRIDUUM"], "periods": ["HOLY_WEEK"], "calendar_metadata": _Obj({"week_of_season": 1, "day_of_season": 0, "day_of_week": 4}), "colors": ["WHITE"], "i18n_def": ["names:thursday_of_the_lords_supper"]}))
        self._new_def("friday_of_the_passion_of_the_lord", _Obj({"precedence": "TRIDUUM_1", "date_def": _Obj({"date_fn": "goodFriday", "year_offset": year_offset}), "seasons": ["PASCHAL_TRIDUUM"], "periods": ["HOLY_WEEK"], "calendar_metadata": _Obj({"week_of_season": 1, "day_of_season": 1, "day_of_week": 5}), "colors": ["RED"], "i18n_def": ["names:friday_of_the_passion_of_the_lord"]}))
        self._new_def("holy_saturday", _Obj({"precedence": "TRIDUUM_1", "date_def": _Obj({"date_fn": "holySaturday", "year_offset": year_offset}), "seasons": ["PASCHAL_TRIDUUM"], "periods": ["HOLY_WEEK"], "calendar_metadata": _Obj({"week_of_season": 1, "day_of_season": 2, "day_of_week": 6}), "colors": [], "i18n_def": ["names:holy_saturday"]}))
        self._new_def("easter_sunday", _Obj({"precedence": "TRIDUUM_1", "date_def": _Obj({"date_fn": "easterSunday", "year_offset": year_offset}), "is_holy_day_of_obligation": True, "seasons": ["PASCHAL_TRIDUUM", "EASTER_TIME"], "periods": ["EASTER_OCTAVE"], "calendar_metadata": _Obj({"week_of_season": 1, "day_of_season": 1, "day_of_week": 0}), "colors": ["WHITE"], "i18n_def": ["names:easter_sunday"]}))

    def easter_time(self, year_offset=0):
        for dow in range(1, 7):
            self._new_def(f"easter_{self._weekdays[dow]}", _Obj({"precedence": "WEEKDAY_OF_EASTER_OCTAVE_2", "date_def": _Obj({"date_fn": "easterSunday", "add_day": dow, "year_offset": year_offset}), "seasons": ["EASTER_TIME"], "periods": ["EASTER_OCTAVE"], "calendar_metadata": _Obj({"week_of_season": 1, "day_of_season": dow + 1, "day_of_week": dow}), "colors": ["WHITE"], "i18n_def": ["seasons:easter_time.octave", _Obj({"dow": dow})]}))
        self._new_def("divine_mercy_sunday", _Obj({"precedence": "PRIVILEGED_SUNDAY_2", "date_def": _Obj({"date_fn": "divineMercySunday", "year_offset": year_offset}), "is_holy_day_of_obligation": True, "seasons": ["EASTER_TIME"], "periods": ["EASTER_OCTAVE"], "calendar_metadata": _Obj({"week_of_season": 2, "day_of_season": 8, "day_of_week": 0}), "colors": ["WHITE"], "i18n_def": ["names:divine_mercy_sunday"]}))
        for i in range(8, 49):
            week = int(i // 7) + 1
            dow = i - (week - 1) * 7
            data = _Obj({"precedence": ("PRIVILEGED_SUNDAY_2" if dow == 0 else "WEEKDAY_13"), "date_def": _Obj({"date_fn": "weekdayOrSundayOfEasterTime", "date_args": [dow, week], "year_offset": year_offset}), "is_holy_day_of_obligation": dow == 0, "seasons": ["EASTER_TIME"], "periods": [], "calendar_metadata": _Obj({"week_of_season": week, "day_of_season": i + 1, "day_of_week": dow}), "colors": ["WHITE"], "i18n_def": (["seasons:easter_time.sunday", _Obj({"week": week})] if dow == 0 else ["seasons:easter_time.weekday", _Obj({"week": week, "dow": dow})])})
            if week == 6 and dow == 4:
                self._new_def("ascension_of_the_lord", _Obj({**data, "precedence": "PROPER_OF_TIME_SOLEMNITY_2", "date_def": _Obj({"date_fn": "ascension", "year_offset": year_offset}), "is_holy_day_of_obligation": True, "calendar_metadata": _Obj({}), "i18n_def": ["names:ascension_of_the_lord"]}))
            self._new_def(f"easter_time_{week}_{self._weekdays[dow]}", data)
        self._new_def("pentecost_sunday", _Obj({"precedence": "PROPER_OF_TIME_SOLEMNITY_2", "date_def": _Obj({"date_fn": "pentecostSunday", "year_offset": year_offset}), "is_holy_day_of_obligation": True, "seasons": ["EASTER_TIME"], "periods": [], "calendar_metadata": _Obj({"week_of_season": 8, "day_of_season": 50, "day_of_week": 0}), "colors": ["RED"], "i18n_def": ["names:pentecost_sunday"]}))

    def ordinary_time(self, year_offset=0):
        self._new_def("most_holy_trinity", _Obj({"precedence": "GENERAL_SOLEMNITY_3", "date_def": _Obj({"date_fn": "trinitySunday", "year_offset": year_offset}), "is_holy_day_of_obligation": True, "seasons": ["ORDINARY_TIME"], "periods": [], "calendar_metadata": _Obj({"day_of_week": 0}), "colors": ["WHITE"], "i18n_def": ["names:most_holy_trinity"]}))
        self._new_def("most_holy_body_and_blood_of_christ", _Obj({"precedence": "GENERAL_SOLEMNITY_3", "date_def": _Obj({"date_fn": "corpusChristi", "year_offset": year_offset}), "is_holy_day_of_obligation": True, "seasons": ["ORDINARY_TIME"], "periods": [], "calendar_metadata": _Obj({}), "colors": ["WHITE"], "i18n_def": ["names:most_holy_body_and_blood_of_christ"]}))
        self._new_def("most_sacred_heart_of_jesus", _Obj({"precedence": "GENERAL_SOLEMNITY_3", "date_def": _Obj({"date_fn": "mostSacredHeartOfJesus", "year_offset": year_offset}), "is_holy_day_of_obligation": False, "seasons": ["ORDINARY_TIME"], "periods": [], "calendar_metadata": _Obj({"day_of_week": 5}), "colors": ["WHITE"], "i18n_def": ["names:most_sacred_heart_of_jesus"]}))
        for i in range(1, 238):
            week = int(i // 7) + 1
            dow = i - (week - 1) * 7
            data = _Obj({"precedence": ("UNPRIVILEGED_SUNDAY_6" if dow == 0 else "WEEKDAY_13"), "date_def": _Obj({"date_fn": "dateOfOrdinaryTime", "date_args": [dow, week], "year_offset": year_offset}), "is_holy_day_of_obligation": dow == 0, "seasons": ["ORDINARY_TIME"], "periods": [], "calendar_metadata": _Obj({"week_of_season": week, "day_of_week": dow}), "colors": ["GREEN"], "i18n_def": (["seasons:ordinary_time.sunday", _Obj({"week": week})] if dow == 0 else ["seasons:ordinary_time.weekday", _Obj({"week": week, "dow": dow})])})
            if week == 3 and dow == 0:
                self._new_def("sunday_of_the_word_of_god", _Obj({**data, "i18n_def": ["names:sunday_of_the_word_of_god"]}))
            elif week == 34 and dow == 0:
                self._new_def("our_lord_jesus_christ_king_of_the_universe", _Obj({**data, "precedence": "GENERAL_SOLEMNITY_3", "colors": ["WHITE"], "i18n_def": ["names:our_lord_jesus_christ_king_of_the_universe"]}))
            else:
                self._new_def(f"ordinary_time_{week}_{self._weekdays[dow]}", data)
