# AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
# Re-run the script to regenerate after updating the romcal TypeScript source.
# romcal version: 3.0.0-dev.125
"""
python-romcal: Python port of the romcal liturgical calendar engine.

Usage::

    from romcal import Romcal
    from romcal.bundles import GeneralRoman_En

    romcal = Romcal(localized_calendar=GeneralRoman_En)
    calendar = romcal.generate_calendar(2026)
    # Returns dict[str, list[LiturgicalDay]]

TS: rites/roman1969/src/index.ts
"""

from romcal.engine import Romcal
from romcal.types import LiturgicalDay, MartyrologyItem, ColorInfo, RomcalBundle
from romcal.constants import (
    Season, Period, Color, Rank,
    PRECEDENCES,
    SUNDAY_CYCLES, WEEKDAY_CYCLES, PSALTER_WEEKS,
    PROPER_OF_TIME_NAME, GENERAL_ROMAN_NAME,
    is_martyr,
)

__all__ = [
    # Public API
    "Romcal",
    # Types
    "LiturgicalDay",
    "MartyrologyItem",
    "ColorInfo",
    "RomcalBundle",
    # Constants
    "Season",
    "Period",
    "Color",
    "Rank",
    "PRECEDENCES",
    "SUNDAY_CYCLES",
    "WEEKDAY_CYCLES",
    "PSALTER_WEEKS",
    "PROPER_OF_TIME_NAME",
    "GENERAL_ROMAN_NAME",
    "is_martyr",
]
