# AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
# Re-run the script to regenerate after updating the romcal TypeScript source.
# romcal version: 3.0.0-dev.125

"""
constants.py — Python string constants mirroring romcal TypeScript enums.

Values are exactly as they appear in the romcal JS output so that bundle JSON
can be used without any translation.

Source: rites/roman1969/src/constants/
"""

# ── Seasons ─────────────────────────────────────────────────────────────────
# TS: constants/seasons.ts (Season enum)
class Season:
    ADVENT = "ADVENT"
    CHRISTMAS_TIME = "CHRISTMAS_TIME"
    LENT = "LENT"
    PASCHAL_TRIDUUM = "PASCHAL_TRIDUUM"
    EASTER_TIME = "EASTER_TIME"
    ORDINARY_TIME = "ORDINARY_TIME"


# ── Periods ─────────────────────────────────────────────────────────────────
# TS: constants/periods.ts (Period enum)
class Period:
    CHRISTMAS_OCTAVE = "CHRISTMAS_OCTAVE"
    DAYS_BEFORE_EPIPHANY = "DAYS_BEFORE_EPIPHANY"
    DAYS_FROM_EPIPHANY = "DAYS_FROM_EPIPHANY"
    CHRISTMAS_TO_PRESENTATION_OF_THE_LORD = "CHRISTMAS_TO_PRESENTATION_OF_THE_LORD"
    PRESENTATION_OF_THE_LORD_TO_HOLY_THURSDAY = "PRESENTATION_OF_THE_LORD_TO_HOLY_THURSDAY"
    HOLY_WEEK = "HOLY_WEEK"
    EASTER_OCTAVE = "EASTER_OCTAVE"
    EARLY_ORDINARY_TIME = "EARLY_ORDINARY_TIME"
    LATE_ORDINARY_TIME = "LATE_ORDINARY_TIME"


# ── Colors ──────────────────────────────────────────────────────────────────
# TS: constants/colors.ts (Colors enum)
class Color:
    RED = "RED"
    ROSE = "ROSE"
    PURPLE = "PURPLE"
    GREEN = "GREEN"
    WHITE = "WHITE"
    GOLD = "GOLD"
    BLACK = "BLACK"


# ── Ranks ───────────────────────────────────────────────────────────────────
# TS: constants/ranks.ts (Ranks enum)
class Rank:
    SOLEMNITY = "SOLEMNITY"
    SUNDAY = "SUNDAY"
    FEAST = "FEAST"
    MEMORIAL = "MEMORIAL"
    OPTIONAL_MEMORIAL = "OPTIONAL_MEMORIAL"
    WEEKDAY = "WEEKDAY"


# ── Precedences ─────────────────────────────────────────────────────────────
# TS: constants/precedences.ts (PRECEDENCES array)
# Array ordering is significant — lower index = higher liturgical priority.
PRECEDENCES: list[str] = [
    "TRIDUUM_1",
    "PROPER_OF_TIME_SOLEMNITY_2",
    "PRIVILEGED_SUNDAY_2",
    "ASH_WEDNESDAY_2",
    "WEEKDAY_OF_HOLY_WEEK_2",
    "WEEKDAY_OF_EASTER_OCTAVE_2",
    "GENERAL_SOLEMNITY_3",
    "COMMEMORATION_OF_ALL_THE_FAITHFUL_DEPARTED_3",
    "PROPER_SOLEMNITY__PRINCIPAL_PATRON_4A",
    "PROPER_SOLEMNITY__DEDICATION_OF_THE_OWN_CHURCH_4B",
    "PROPER_SOLEMNITY__TITLE_OF_THE_OWN_CHURCH_4C",
    "PROPER_SOLEMNITY__TITLE_OR_FOUNDER_OR_PRIMARY_PATRON_OF_A_RELIGIOUS_ORG_4D",
    "GENERAL_LORD_FEAST_5",
    "UNPRIVILEGED_SUNDAY_6",
    "GENERAL_FEAST_7",
    "PROPER_FEAST__PRINCIPAL_PATRON_OF_A_DIOCESE_8A",
    "PROPER_FEAST__DEDICATION_OF_THE_CATHEDRAL_CHURCH_8B",
    "PROPER_FEAST__PRINCIPAL_PATRON_OF_A_REGION_8C",
    "PROPER_SOLEMNITY__TITLE_OR_FOUNDER_OR_PRIMARY_PATRON_OF_A_RELIGIOUS_ORG_8D",
    "PROPER_FEAST__TO_AN_INDIVIDUAL_CHURCH_8E",
    "PROPER_FEAST_8F",
    "PRIVILEGED_WEEKDAY_9",
    "GENERAL_MEMORIAL_10",
    "PROPER_MEMORIAL__SECOND_PATRON_11A",
    "PROPER_MEMORIAL_11B",
    "WEEKDAY_13",
    "OPTIONAL_MEMORIAL_12",
]

# ── Rank ↔ Precedence mapping ───────────────────────────────────────────────
# TS: constants/ranks.ts (RanksFromPrecedence)
RANKS_FROM_PRECEDENCE: dict[str, str] = {
    "TRIDUUM_1": "WEEKDAY",
    "PROPER_OF_TIME_SOLEMNITY_2": "SOLEMNITY",
    "PRIVILEGED_SUNDAY_2": "SUNDAY",
    "ASH_WEDNESDAY_2": "WEEKDAY",
    "WEEKDAY_OF_HOLY_WEEK_2": "WEEKDAY",
    "WEEKDAY_OF_EASTER_OCTAVE_2": "SOLEMNITY",
    "GENERAL_SOLEMNITY_3": "SOLEMNITY",
    "COMMEMORATION_OF_ALL_THE_FAITHFUL_DEPARTED_3": "FEAST",
    "PROPER_SOLEMNITY__PRINCIPAL_PATRON_4A": "SOLEMNITY",
    "PROPER_SOLEMNITY__DEDICATION_OF_THE_OWN_CHURCH_4B": "SOLEMNITY",
    "PROPER_SOLEMNITY__TITLE_OF_THE_OWN_CHURCH_4C": "SOLEMNITY",
    "PROPER_SOLEMNITY__TITLE_OR_FOUNDER_OR_PRIMARY_PATRON_OF_A_RELIGIOUS_ORG_4D": "SOLEMNITY",
    "GENERAL_LORD_FEAST_5": "FEAST",
    "UNPRIVILEGED_SUNDAY_6": "SUNDAY",
    "GENERAL_FEAST_7": "FEAST",
    "PROPER_FEAST__PRINCIPAL_PATRON_OF_A_DIOCESE_8A": "FEAST",
    "PROPER_FEAST__DEDICATION_OF_THE_CATHEDRAL_CHURCH_8B": "FEAST",
    "PROPER_FEAST__PRINCIPAL_PATRON_OF_A_REGION_8C": "FEAST",
    "PROPER_SOLEMNITY__TITLE_OR_FOUNDER_OR_PRIMARY_PATRON_OF_A_RELIGIOUS_ORG_8D": "FEAST",
    "PROPER_FEAST__TO_AN_INDIVIDUAL_CHURCH_8E": "FEAST",
    "PROPER_FEAST_8F": "FEAST",
    "PRIVILEGED_WEEKDAY_9": "WEEKDAY",
    "GENERAL_MEMORIAL_10": "MEMORIAL",
    "PROPER_MEMORIAL__SECOND_PATRON_11A": "MEMORIAL",
    "PROPER_MEMORIAL_11B": "MEMORIAL",
    "WEEKDAY_13": "WEEKDAY",
    "OPTIONAL_MEMORIAL_12": "OPTIONAL_MEMORIAL",
}

# Alias for auto-translated modules that reference the TS name RanksFromPrecedence.
RanksFromPrecedence = RANKS_FROM_PRECEDENCE

# ── Cycle constants ──────────────────────────────────────────────────────────
# TS: constants/cycles.ts

SUNDAY_CYCLES: list[str] = ['YEAR_A', 'YEAR_B', 'YEAR_C']
WEEKDAY_CYCLES: list[str] = ['YEAR_1', 'YEAR_2']
PSALTER_WEEKS: list[str] = ['WEEK_1', 'WEEK_2', 'WEEK_3', 'WEEK_4']

# ── Calendar name constants ──────────────────────────────────────────────────
# TS: constants/general-calendar-names.ts
PROPER_OF_TIME_NAME = "ProperOfTime"
GENERAL_ROMAN_NAME  = "GeneralRoman"
GENERAL_ROMAN_ID    = "general_roman"

# ── Martyrology helpers ──────────────────────────────────────────────────────
# TS: constants/martyrology-metadata.ts (isMartyr)
# Martyr title values from constants.json['Title']
_MARTYR_TITLES = {
    "MARTYR",
    "PROTO_MARTYR_OF_OCEANIA",
    "THE_FIRST_MARTYR",
}


def is_martyr(titles: list[str]) -> bool:
    """Return True if any title in the list indicates martyrdom."""
    return any(t in _MARTYR_TITLES for t in (titles or []))
