# AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
# Re-run the script to regenerate after updating the romcal TypeScript source.
# romcal version: 3.0.0-dev.125
"""
engine.py — Romcal public API (synchronous Python version).

Mirrors the JS Romcal class from rites/roman1969/src/index.ts,
but without Promises — all methods return values directly.

Usage::

    from romcal import Romcal
    from romcal.bundles import GeneralRoman_En

    romcal = Romcal(localized_calendar=GeneralRoman_En)
    calendar = romcal.generate_calendar(2026)
    # Returns dict[str, list[LiturgicalDay]]

AUTO-TRANSLATED from rites/roman1969/src/index.ts.
"""

from __future__ import annotations
from collections import defaultdict
from types import SimpleNamespace
from typing import Any

from romcal.types import LiturgicalDay, RomcalBundle
from romcal.models.config import RomcalConfig
from romcal.models.liturgical_day_config import LiturgicalDayConfig
from romcal.models.calendar_engine import CalendarEngine


class _NS(SimpleNamespace):
    """SimpleNamespace that returns None for missing attributes (mirrors TS optional object keys)."""
    def __getattr__(self, name: str):
        return None


def _resolve_bundle(localized_calendar: Any) -> RomcalBundle:
    """
    Convert a bundle proxy or RomcalBundle to a concrete RomcalBundle.
    Python-specific: the TS API receives RomcalConfigInput directly; the Python
    API accepts a bundle or bundle proxy and converts it here.
    """
    if isinstance(localized_calendar, RomcalBundle):
        return localized_calendar
    if hasattr(localized_calendar, "_bundle") and localized_calendar._bundle:
        return localized_calendar._bundle
    loader = getattr(localized_calendar, "_load_bundle", None)
    if loader:
        return loader(localized_calendar._calendar_name, localized_calendar._locale_code)
    raise TypeError(f"Cannot resolve bundle from {type(localized_calendar)!r}")


class Romcal:
    """
    Main entry point. Synchronous equivalent of the JS Romcal class.

    TS: rites/roman1969/src/index.ts (Romcal class)
    """

    # Python-specific constructor: the TS constructor takes RomcalConfigInput;
    # the Python API takes localized_calendar (a bundle or proxy) for convenience.
    # TS: constructor(config?: RomcalConfigInput) { this.#config = new RomcalConfig(config); }
    def __init__(self, localized_calendar: Any = None) -> None:
        """
        :param localized_calendar: A RomcalBundle or bundle proxy from romcal.bundles.
        """
        bundle = _resolve_bundle(localized_calendar)
        config_input = SimpleNamespace(
            localized_calendar=bundle,
            scope="gregorian",
            epiphany_on_sunday=None,
            corpus_christi_on_sunday=None,
            ascension_on_sunday=None,
            elevated_memorial_ids=None,
            easter_calculation_type=None,
            output_options=None,
        )
        # TS: Record<K,V> = {} — use defaultdict so missing-key access returns None (JS semantics)
        self._computed_calendars: dict = defaultdict(lambda: None)
        self._dates_cache: dict = defaultdict(lambda: None)
        self._config = RomcalConfig(config_input)

    @property
    def config(self):
        return self._config.to_object()

    @staticmethod
    def _sanitize_year(year=None):
        y = (int(year[:4]) if isinstance(year, str) else year)
        if (y != None and not isinstance(y, int)) or (isinstance(y, int) and (y < 0 or y > 9999)):
            raise RuntimeError("The provided year is incorrect")
        return y

    def dates(self, year=None):
        y = Romcal._sanitize_year(year)
        ld_config = LiturgicalDayConfig(self._config, y)
        if self._dates_cache[ld_config.year]:
            return self._dates_cache[ld_config.year]
        self._dates_cache[ld_config.year] = ld_config.dates
        return self._dates_cache[ld_config.year]

    def get_one_liturgical_day(self, id_, options=None):
        if options is None: options = _NS(**_Obj({"compute_in_whole_year": False}))
        y = Romcal._sanitize_year(options.year)
        ld_config = LiturgicalDayConfig(self._config, y)
        self.get_all_definitions()
        partial_ld = CalendarEngine(self._config, ld_config).get_one_liturgical_day(id_)
        if not options.compute_in_whole_year:
            return partial_ld
        if not partial_ld:
            return partial_ld
        _then_result = self.generate_calendar(ld_config.year)
        value = _then_result
        return next((d for d in [item for sub in list(value.values()) for item in (sub if isinstance(sub, list) else [sub])] if d.id == id_), None)

    def generate_calendar(self, year=None):
        y = Romcal._sanitize_year(year)
        ld_config = LiturgicalDayConfig(self._config, y)
        if self._computed_calendars[ld_config.year]:
            return self._computed_calendars[ld_config.year]
            return
        self.get_all_definitions()
        self._computed_calendars[ld_config.year] = CalendarEngine(self._config, ld_config).generate_calendar()
        return self._computed_calendars[ld_config.year]

    def get_all_definitions(self):
        [cal.build_all_definitions() for cal in self._config.calendars_def]
        return self._config.liturgical_day_def

    def get_version(self):
        return Romcal.get_version()

    @staticmethod
    def get_version():
        return version

