# AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
# Re-run the script to regenerate after updating the romcal TypeScript source.
# romcal version: 3.0.0-dev.125
"""
types.py — Python dataclasses mirroring romcal TypeScript types.

TS sources:
  rites/roman1969/src/types/liturgical-day.ts
  rites/roman1969/src/types/martyrology.ts
  rites/roman1969/src/types/bundle.ts
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any


@dataclass
class ColorInfo:
    """Color constant + localized name. TS: Color enum."""
    id: str    # e.g. "WHITE"
    name: str  # localized, e.g. "White"


@dataclass
class MartyrologyItem:
    """
    TS: MartyrologyItem in types/martyrology.ts.
    Represents a saint or group in the martyrology catalog.
    """
    id: str
    name: str = ""
    titles: list[str] = field(default_factory=list)
    canonization_level: str | None = None   # "BLESSED" | "SAINT" | None
    date_of_birth: str | None = None
    date_of_death: str | None = None
    date_of_beatification: str | None = None
    date_of_canonization: str | None = None
    sex: str | None = None                  # "MALE" | "FEMALE" | None
    count: int | str | None = None          # int or "many"
    hide_canonization_level: bool = False
    hide_titles: bool = False
    date_of_dedication: str | None = None


@dataclass
class LiturgicalDay:
    """
    TS: LiturgicalDay in models/liturgical-day.ts.

    A single liturgical observance on a calendar date.  A date may have
    multiple entries (winner first, optional memorials following).
    """
    id: str
    name: str
    date: str                                         # ISO YYYY-MM-DD
    rank: str                                         # Rank constant string
    rank_name: str                                    # localized rank name
    colors: list[ColorInfo] = field(default_factory=list)
    seasons: list[str] = field(default_factory=list)
    season_names: list[str] = field(default_factory=list)
    periods: list[str] = field(default_factory=list)
    from_calendar_id: str = ""
    is_holy_day_of_obligation: bool = False
    is_optional: bool = False
    allow_similar_rank_items: bool = False
    week_of_season: int | None = None
    day_of_season: int | None = None
    day_of_week: int = 0                             # 0=Sunday … 6=Saturday
    nth_day_of_week_in_month: int = 0
    start_of_season: str = ""
    end_of_season: str = ""
    start_of_liturgical_year: str = ""
    end_of_liturgical_year: str = ""
    sunday_cycle: str = ""                            # "YEAR_A" | "YEAR_B" | "YEAR_C"
    weekday_cycle: str = ""                           # "YEAR_1" | "YEAR_2"
    psalter_week: str = "WEEK_1"                      # "WEEK_1" … "WEEK_4"
    proper_cycle: str = ""                            # "PROPER_OF_TIME" | "PROPER_OF_SAINTS"
    martyrology: list[MartyrologyItem] = field(default_factory=list)
    titles: list[str] = field(default_factory=list)
    commons_def: list[str] = field(default_factory=list)
    alternative_transfer_date_defs: list[dict[str, Any]] = field(default_factory=list)
    from_extended_calendars: list[dict[str, Any]] = field(default_factory=list)
    calendar: dict[str, Any] = field(default_factory=dict)


def is_liturgical_day_proper_of_time_input(input_) -> bool:
    """
    Python port of isLiturgicalDayProperOfTimeInput() from types/liturgical-day.ts.
    TS type guard: 'calendarMetadata' in input — checks KEY PRESENCE, not value.

    The Proper of Time always adds calendarMetadata; bundle inputs never do.

    IMPORTANT: use the `in` operator directly — it works for dicts, _Obj (which
    implements __contains__), and any other mapping-like object.  Never use
    getattr(x, "__dict__", {}) because _Obj uses __slots__ and has no __dict__.
    """
    try:
        return "calendar_metadata" in input_ or "calendarMetadata" in input_
    except TypeError:
        return False


@dataclass
class RomcalBundle:
    """
    TS: RomcalBundleObject in types/bundle.ts.

    Holds all resolved data for a particular calendar + locale combination.
    Loaded from JSON files extracted by scripts/extract.ts.
    """
    calendar_name: str
    particular_config: dict[str, Any]
    inputs: dict[str, Any]       # merged calendar inputs (after inheritance)
    martyrology: dict[str, Any]  # full martyrology catalog
    i18n: dict[str, Any]         # locale data (primary locale)
    i18n_fallback: dict[str, Any] = field(default_factory=dict)  # "en" fallback
