# AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
# Re-run the script to regenerate after updating the romcal TypeScript source.
# romcal version: 3.0.0-dev.125

"""
models/bundle.py — Python port of romcal RomcalBundle class.

AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
"""

from __future__ import annotations

from romcal.types import BaseRomcalBundle
from romcal.types import BundleInputs, ParticularConfig

class RomcalBundle:
    calendar_name = None
    particular_config = None
    inputs = None
    martyrology = None
    i18n = None
    def __init__(self, input_):
        self.calendar_name = input_.calendar_name
        self.particular_config = input_.particular_config
        self.inputs = input_.inputs
        self.martyrology = input_.martyrology
        self.i18n = input_.i18n

