# AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
# Re-run the script to regenerate after updating the romcal TypeScript source.
# romcal version: 3.0.0-dev.125

"""
calendar_engine.py — Python port of romcal Calendar class.

AUTO-TRANSLATED from rites/roman1969/src/models/calendar.ts.
"""

from __future__ import annotations
import functools

from romcal.utils.objects import _Obj
import math
from romcal.constants import PROPER_OF_TIME_NAME
from romcal.constants import PRECEDENCES
from romcal.utils.dates import Dates, date_difference, is_valid_date
from romcal.models.config import RomcalConfig
from romcal.models.liturgical_day import LiturgicalDay
from romcal.models.liturgical_day_config import LiturgicalDayConfig
from romcal.models.liturgical_day_def import LiturgicalDayDef

class CalendarEngine:
    dates = None
    def __init__(self, config, liturgical_day_config):
        self._config = None
        self._liturgical_day_config = None
        self._start_of_seasons_dic = _Obj({})
        self._end_of_seasons_dic = _Obj({})
        self._start_of_later_ordinary_time = None
        self._config = config
        self._liturgical_day_config = liturgical_day_config
        self.dates = Dates(config, liturgical_day_config.year)
        self._start_of_later_ordinary_time = self.dates.mary_mother_of_the_church()
    def _build_calendar_metadata(self, def_, date, base_data):
        current_year = self._liturgical_day_config.year
        if self._config.scope == "gregorian" and self._liturgical_day_config.dates.first_sunday_of_advent(self._liturgical_day_config.year) <= date:
            current_year += 1
        start_of_seasons_dic = self._start_of_seasons_dic[current_year] if self._start_of_seasons_dic[current_year] is not None else self._liturgical_day_config.dates.start_of_seasons(current_year)
        end_of_seasons_dic = self._end_of_seasons_dic[current_year] if self._end_of_seasons_dic[current_year] is not None else self._liturgical_day_config.dates.end_of_seasons(current_year)
        start_of_season = (start_of_seasons_dic[def_.seasons[0]] if len(def_.seasons) else None)
        end_of_season = (end_of_seasons_dic[def_.seasons[0]] if len(def_.seasons) else None)
        is_lent = ("LENT" in ((getattr(base_data, 'seasons', None) if getattr(base_data, 'seasons', None) is not None else def_.seasons)))
        is_late_ordinary_time = ("ORDINARY_TIME" in ((getattr(base_data, 'seasons', None) if getattr(base_data, 'seasons', None) is not None else def_.seasons))) and date >= self._start_of_later_ordinary_time
        day_of_season = ((getattr(getattr(base_data, 'calendar', None), 'day_of_season', None) if getattr(getattr(base_data, 'calendar', None), 'day_of_season', None) is not None else def_.calendar_metadata.day_of_season) if (getattr(getattr(base_data, 'calendar', None), 'day_of_season', None) if getattr(getattr(base_data, 'calendar', None), 'day_of_season', None) is not None else def_.calendar_metadata.day_of_season) is not None else ((abs((start_of_season) - (date)).days + 1 if start_of_season else float('nan'))))
        if is_late_ordinary_time:
            day_of_season -= 96
        week_of_season_offset = (-1 if is_lent else 0)
        week_of_season = ((getattr(getattr(base_data, 'calendar', None), 'week_of_season', None) if getattr(getattr(base_data, 'calendar', None), 'week_of_season', None) is not None else def_.calendar_metadata.week_of_season) if (getattr(getattr(base_data, 'calendar', None), 'week_of_season', None) if getattr(getattr(base_data, 'calendar', None), 'week_of_season', None) is not None else def_.calendar_metadata.week_of_season) is not None else ((-(-((day_of_season + (start_of_season.weekday() + 1) % 7)) // (7)) + week_of_season_offset if start_of_season else float('nan'))))
        if is_late_ordinary_time:
            week_of_season = (math.ceil(34 - abs((end_of_season) - (date)).days / 7) if end_of_season else float('nan'))
        return _Obj({"week_of_season": week_of_season, "day_of_season": day_of_season, "day_of_week": ((getattr(getattr(base_data, 'calendar', None), 'day_of_week', None) if getattr(getattr(base_data, 'calendar', None), 'day_of_week', None) is not None else def_.calendar_metadata.day_of_week) if (getattr(getattr(base_data, 'calendar', None), 'day_of_week', None) if getattr(getattr(base_data, 'calendar', None), 'day_of_week', None) is not None else def_.calendar_metadata.day_of_week) is not None else (date.weekday() + 1) % 7), "nth_day_of_week_in_month": -(-(date.day) // (7)), "start_of_season": (start_of_season.isoformat()[0:10] if start_of_season else ""), "end_of_season": (end_of_season.isoformat()[0:10] if end_of_season else ""), "start_of_liturgical_year": start_of_seasons_dic["ADVENT"].isoformat()[0:10], "end_of_liturgical_year": end_of_seasons_dic["ORDINARY_TIME"].isoformat()[0:10], "seasons": (getattr(base_data, 'seasons', None) if getattr(base_data, 'seasons', None) is not None else def_.seasons)})
    def _build_dates_data(self):
        built_data = _Obj({"by_ids": _Obj({}), "dates_index": _Obj({})})
        for def_ in list(self._config.liturgical_day_def.values()):
            is_from_proper_of_time = def_.from_calendar_id == PROPER_OF_TIME_NAME or (len(def_.from_extended_calendars) > 0 and def_.from_extended_calendars[0].from_calendar_id == PROPER_OF_TIME_NAME)
            previous_year_date = (self._liturgical_day_config.build_date(def_, -1) if not is_from_proper_of_time and self._config.scope == "liturgical" else None)
            current_year_date = self._liturgical_day_config.build_date(def_)
            def _reduce_fn_1(acc, d):
                if d and is_valid_date(d):
                    acc.append(d)
                return acc
            
            for date in functools.reduce(_reduce_fn_1, [previous_year_date, current_year_date], []):
                date_str = date.isoformat()[0:10]
                if not is_from_proper_of_time and not built_data.dates_index[date_str]:
                    continue
                base_data = (None if is_from_proper_of_time else next((d for d in built_data.by_ids[built_data.dates_index[date_str][0]] if d.date == date.isoformat()[0:10]), None) or None)
                calendar = (self._build_calendar_metadata(def_, date, base_data) if is_from_proper_of_time else base_data.calendar)
                weekday = (base_data if base_data and any(r == def_.rank for r in ["FEAST", "MEMORIAL", "OPTIONAL_MEMORIAL"]) else None)
                built_data.by_ids[def_.id] = [*((built_data.by_ids[def_.id] if built_data.by_ids[def_.id] is not None else [])), LiturgicalDay(def_, date, self._liturgical_day_config, calendar, base_data, weekday)]
                built_data.dates_index[date_str] = [*((built_data.dates_index[date_str] if built_data.dates_index[date_str] is not None else [])), def_.id]
        built_data.dates_index = functools.reduce(lambda obj, id_: (_Obj({**obj, id_: built_data.dates_index[id_]})), sorted(list(built_data.dates_index.keys())), _Obj({}))
        return built_data
    def get_one_liturgical_day(self, id_):
        if not (id_ in self._config.liturgical_day_def):
            return None
        def_ = self._config.liturgical_day_def[id_]
        date = self._liturgical_day_config.build_date(def_)
        if not date or not is_valid_date(date):
            return None
        calendar = self._build_calendar_metadata(def_, date, None)
        return LiturgicalDay(def_, date, self._liturgical_day_config, calendar, None, None)
    def generate_calendar(self):
        final_data = _Obj({})
        built_data = self._build_dates_data()
        for date_str in list(built_data.dates_index.keys()):
            def _reduce_fn_2(acc, id_):
                item = next((d for d in built_data.by_ids[id_] if d.date == date_str), None)
                if item:
                    acc.append(item)
                return acc
            
            def _cmp_3(_p0, _p1):
                first_precedence = _p0.precedence
                first_allow_similar_rank_items = _p0.allow_similar_rank_items
                first_is_optional = _p0.is_optional
                next_precedence = _p1.precedence
                next_allow_similar_rank_items = _p1.allow_similar_rank_items
                next_is_optional = _p1.is_optional
                if first_is_optional == next_is_optional:
                    if first_allow_similar_rank_items == next_allow_similar_rank_items:
                        type1 = (PRECEDENCES.index(first_precedence) if first_precedence in PRECEDENCES else -1)
                        type2 = (PRECEDENCES.index(next_precedence) if next_precedence in PRECEDENCES else -1)
                        if type1 < type2:
                            return -1
                        if type1 > type2:
                            return 1
                        return 0
                    return (-1 if first_allow_similar_rank_items else 1)
                return (1 if first_is_optional else -1)
            
            dates = sorted(functools.reduce(_reduce_fn_2, built_data.dates_index[date_str], []), key=functools.cmp_to_key(_cmp_3))
            thursday_of_the_lords_supper = None
            if dates[0].id == "thursday_of_the_lords_supper":
                thursday_of_the_lords_supper = dates.pop(0)
            default_liturgical_day = dates[0]
            optional_memorials = []
            if (default_liturgical_day.precedence == "PRIVILEGED_WEEKDAY_9" or default_liturgical_day.precedence == "WEEKDAY_13") and not ("HOLY_WEEK" in default_liturgical_day.periods):
                optional_memorials = (optional_memorials + (lambda _c: _c if isinstance(_c, list) else [_c])(([(setattr(d, 'is_optional', True) or d) for d in [d for d in dates[1:] if any(p == d.precedence for p in ["GENERAL_MEMORIAL_10", "PROPER_MEMORIAL__SECOND_PATRON_11A", "PROPER_MEMORIAL_11B", "OPTIONAL_MEMORIAL_12"]) or d.is_optional]])))
            if default_liturgical_day.allow_similar_rank_items and len(dates) > 1:
                check_next_items = lambda d: d.rank == default_liturgical_day.rank and d.precedence != "OPTIONAL_MEMORIAL_12" and not (d.id in [om.id for om in optional_memorials])
                next_allowing_similar_items = [d for d in dates[1:] if d.allow_similar_rank_items and check_next_items(d)]
                optional_memorials = [*optional_memorials, *next_allowing_similar_items]
                next_item = next((d for d in dates[1:] if not d.allow_similar_rank_items and check_next_items(d)), None)
                if next_item:
                    optional_memorials.append(next_item)
            if len(dates) > 1:
                optional_day_ids = [d.id for d in optional_memorials]
                default_precedence_index = (PRECEDENCES.index(default_liturgical_day.precedence) if default_liturgical_day.precedence in PRECEDENCES else -1)
                optional_memorials = (optional_memorials + (lambda _c: _c if isinstance(_c, list) else [_c])(([d for d in dates[1:] if d.is_optional and (PRECEDENCES.index(d.precedence) if d.precedence in PRECEDENCES else -1) >= default_precedence_index and not (d.id in optional_day_ids)])))
            final_data[date_str] = [default_liturgical_day, *optional_memorials, *(([thursday_of_the_lords_supper] if thursday_of_the_lords_supper else []))]
        if getattr(getattr(self._config, 'output_options', None), 'calculate_properties', None):
            calculated_data = _Obj({})
            for date_str in list(final_data.keys()):
                calculated_data[date_str] = [d.to_json() for d in final_data[date_str]]
            return calculated_data
        return final_data

