# AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
# Re-run the script to regenerate after updating the romcal TypeScript source.
# romcal version: 3.0.0-dev.125

"""
calendar_def.py — Python port of romcal CalendarDef class.

AUTO-TRANSLATED from rites/roman1969/src/models/calendar-def.ts.
"""

from __future__ import annotations
from typing import Any

from romcal.utils.objects import _Obj
import re
from romcal.models.liturgical_day_def import LiturgicalDayDef

import re as _re_camel

def _camel_to_snake_key(name: str) -> str:
    """Convert a camelCase dict key to snake_case."""
    s = _re_camel.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    return _re_camel.sub(r"([a-z\d])([A-Z])", r"\1_\2", s).lower()


def _deep_ns(val):
    """
    Recursively wrap plain dicts in _Obj, converting camelCase keys to snake_case.
    """
    if isinstance(val, dict):
        return _Obj({_camel_to_snake_key(k): _deep_ns(v) for k, v in val.items()})
    if isinstance(val, list):
        return [_deep_ns(item) for item in val]
    return val


def _camel_dict_to_ns(d: dict) -> _Obj:
    """
    Convert a camelCase-keyed bundle input dict to a snake_case-keyed _Obj.
    LiturgicalDayDef.__init__ accesses input via snake_case attribute names.
    """
    return _deep_ns(d)


class CalendarDef:
    dates = None
    parent_calendars = None
    parent_calendar_instances = None
    particular_config = None
    @property
    def calendar_name(self):
        if not self._calendar_name:
            self._calendar_name = "_".join([p for p in re.split(r"(?=[A-Z])", type(self).__name__) if p]).lower()
        return self._calendar_name
    def __init__(self, config, inputs=None):
        self._config = None
        self.inputs = _Obj({})
        self._definitions_built = False
        self._calendar_name = None
        self._config = config
        self.dates = self._config.dates
        if inputs:
            self.inputs = inputs
    def update_config(self, input_=None):
        if self.parent_calendars:
            _map_result_1 = []
            for parent_cal in self.parent_calendars:
                parent_cal_instance = ParentCal(self._config)
                parent_cal_instance.update_config(input_)
                _map_result_1.append(parent_cal_instance)

            self.parent_calendar_instances = _map_result_1
        self._config.epiphany_on_sunday = ((getattr(input_, 'epiphany_on_sunday', None) if getattr(input_, 'epiphany_on_sunday', None) is not None else getattr(self.particular_config, 'epiphany_on_sunday', None)) if (getattr(input_, 'epiphany_on_sunday', None) if getattr(input_, 'epiphany_on_sunday', None) is not None else getattr(self.particular_config, 'epiphany_on_sunday', None)) is not None else self._config.epiphany_on_sunday)
        self._config.ascension_on_sunday = ((getattr(input_, 'ascension_on_sunday', None) if getattr(input_, 'ascension_on_sunday', None) is not None else getattr(self.particular_config, 'ascension_on_sunday', None)) if (getattr(input_, 'ascension_on_sunday', None) if getattr(input_, 'ascension_on_sunday', None) is not None else getattr(self.particular_config, 'ascension_on_sunday', None)) is not None else self._config.ascension_on_sunday)
        self._config.corpus_christi_on_sunday = ((getattr(input_, 'corpus_christi_on_sunday', None) if getattr(input_, 'corpus_christi_on_sunday', None) is not None else getattr(self.particular_config, 'corpus_christi_on_sunday', None)) if (getattr(input_, 'corpus_christi_on_sunday', None) if getattr(input_, 'corpus_christi_on_sunday', None) is not None else getattr(self.particular_config, 'corpus_christi_on_sunday', None)) is not None else self._config.corpus_christi_on_sunday)
    def _retrieve_parent_cal_inputs(self, parent_cal):
        if parent_cal.parent_calendar_instances:
            for parent in parent_cal.parent_calendar_instances:
                self._retrieve_parent_cal_inputs(parent)
        parent_cal.build_all_definitions()
    def build_all_definitions(self):
        if self._definitions_built:
            return
        inputs = list(self.inputs.keys())
        if self.parent_calendar_instances:
            for parent in self.parent_calendar_instances:
                self._retrieve_parent_cal_inputs(parent)
        for id_ in inputs:
            input_values = ((self.inputs[id_]) if isinstance(self.inputs[id_], list) else [self.inputs[id_]])
            [self._build_definition(id_, input_) for input_ in input_values]
        self._definitions_built = True
    def _build_definition(self, id_, input_):
        input_ = _camel_dict_to_ns(input_)
        return LiturgicalDayDef(id_, _Obj({"date_def": input_.date_def, "date_exceptions": input_.date_exceptions, "alternative_transfer_date_defs": input_.alternative_transfer_date_defs, "precedence": input_.precedence, "allow_similar_rank_items": input_.allow_similar_rank_items, "custom_locale_id": input_.custom_locale_id, "is_holy_day_of_obligation": input_.is_holy_day_of_obligation, "commons_def": input_.commons_def, "is_optional": input_.is_optional, "colors": input_.colors, "martyrology": input_.martyrology, "titles": input_.titles, "proper_cycle": input_.proper_cycle, "drop": input_.drop}), (input_.from_calendar_id if input_.from_calendar_id is not None else self.calendar_name), self._config)

