# AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
# Re-run the script to regenerate after updating the romcal TypeScript source.
# romcal version: 3.0.0-dev.125

"""
config.py — Python port of romcal RomcalConfig class.

AUTO-TRANSLATED from rites/roman1969/src/models/config.ts.
"""

from __future__ import annotations

from romcal.i18n import I18n
from romcal.utils.objects import _Obj
from romcal.proper_of_time.proper_of_time import ProperOfTime
from romcal.utils.dates import Dates
from romcal.utils.numbers import to_roman_number
from romcal.utils.string import sanitize_locale_id
from romcal.models.calendar_def import CalendarDef

class RomcalConfig:
    localized_calendar = None
    locale_id = None
    calendar_name = None
    epiphany_on_sunday = None
    corpus_christi_on_sunday = None
    ascension_on_sunday = None
    easter_calculation_type = None
    scope = None
    i18next = None
    dates = None
    martyrology_catalog = None
    calendars_def = None
    output_options = None
    def clone(self):
        return RomcalConfig(_Obj({**self._input}))
    def __init__(self, config=None, martyrology_catalog=None, locale=None, particular_calendar=None):
        self._input = None
        self.elevated_memorial_ids = []
        self.cycles_cache = _Obj({})
        self.liturgical_day_def = _Obj({})
        self._input = config or _Obj({})
        if getattr(config, 'localized_calendar', None):
            self.localized_calendar = config.localized_calendar
        self.easter_calculation_type = (getattr(config, 'easter_calculation_type', None) if getattr(config, 'easter_calculation_type', None) is not None else "gregorian")
        self.scope = (getattr(config, 'scope', None) if getattr(config, 'scope', None) is not None else "gregorian")
        self.epiphany_on_sunday = ((getattr(config, 'epiphany_on_sunday', None) if getattr(config, 'epiphany_on_sunday', None) is not None else getattr(getattr(self.localized_calendar, 'particular_config', None), 'epiphany_on_sunday', None)) if (getattr(config, 'epiphany_on_sunday', None) if getattr(config, 'epiphany_on_sunday', None) is not None else getattr(getattr(self.localized_calendar, 'particular_config', None), 'epiphany_on_sunday', None)) is not None else False)
        self.corpus_christi_on_sunday = ((getattr(config, 'corpus_christi_on_sunday', None) if getattr(config, 'corpus_christi_on_sunday', None) is not None else getattr(getattr(self.localized_calendar, 'particular_config', None), 'corpus_christi_on_sunday', None)) if (getattr(config, 'corpus_christi_on_sunday', None) if getattr(config, 'corpus_christi_on_sunday', None) is not None else getattr(getattr(self.localized_calendar, 'particular_config', None), 'corpus_christi_on_sunday', None)) is not None else True)
        self.ascension_on_sunday = ((getattr(config, 'ascension_on_sunday', None) if getattr(config, 'ascension_on_sunday', None) is not None else getattr(getattr(self.localized_calendar, 'particular_config', None), 'ascension_on_sunday', None)) if (getattr(config, 'ascension_on_sunday', None) if getattr(config, 'ascension_on_sunday', None) is not None else getattr(getattr(self.localized_calendar, 'particular_config', None), 'ascension_on_sunday', None)) is not None else False)
        self.elevated_memorial_ids = (getattr(config, 'elevated_memorial_ids', None) if getattr(config, 'elevated_memorial_ids', None) is not None else [])
        locale_obj = (getattr(self.localized_calendar, 'i18n', None) if getattr(self.localized_calendar, 'i18n', None) is not None else locale)
        self.locale_id = (sanitize_locale_id(locale_obj.id) if getattr(locale_obj, 'id', None) else "dev")
        self.i18next = I18n({})
        if locale_obj:
            self._add_resource_bundles(locale_obj)
        self.dates = Dates
        self.calendars_def = []
        self.martyrology_catalog = ((getattr(self.localized_calendar, 'martyrology', None) if getattr(self.localized_calendar, 'martyrology', None) is not None else martyrology_catalog) if (getattr(self.localized_calendar, 'martyrology', None) if getattr(self.localized_calendar, 'martyrology', None) is not None else martyrology_catalog) is not None else (_Obj({})))
        self.calendars_def.append(ProperOfTime(self))
        if getattr(config, 'localized_calendar', None):
            self.calendars_def.append(CalendarDef(self, config.localized_calendar.inputs))
        else:
            self.calendars_def.append(GeneralRoman(self))
            if ParticularCalendar:
                self.calendars_def.append(ParticularCalendar(self))
        self.calendar_name = (getattr(getattr(config, 'localized_calendar', None), 'calendar_name', None) if getattr(getattr(config, 'localized_calendar', None), 'calendar_name', None) is not None else self.calendars_def[len(self.calendars_def) - 1].calendar_name)
        [cal.update_config(config) for cal in self.calendars_def]
        self.output_options = (getattr(self._input, 'output_options', None) if getattr(self._input, 'output_options', None) is not None else _Obj({"calculate_properties": False}))
    def _add_resource_bundles(self, locale):
        self.i18next.add_resource_bundle(locale.id, "seasons", (locale.seasons if locale.seasons is not None else _Obj({})))
        self.i18next.add_resource_bundle(locale.id, "periods", (locale.periods if locale.periods is not None else _Obj({})))
        self.i18next.add_resource_bundle(locale.id, "ranks", (locale.ranks if locale.ranks is not None else _Obj({})))
        self.i18next.add_resource_bundle(locale.id, "cycles", (locale.cycles if locale.cycles is not None else _Obj({})))
        self.i18next.add_resource_bundle(locale.id, "weekdays", (locale.weekdays if locale.weekdays is not None else _Obj({})))
        self.i18next.add_resource_bundle(locale.id, "months", (locale.months if locale.months is not None else _Obj({})))
        self.i18next.add_resource_bundle(locale.id, "colors", (locale.colors if locale.colors is not None else _Obj({})))
        self.i18next.add_resource_bundle(locale.id, "ordinals", (locale.ordinals if locale.ordinals is not None else _Obj({})))
        self.i18next.add_resource_bundle(locale.id, "names", (locale.names if locale.names is not None else _Obj({})))
    def get_liturgical_color_names(self, colors):
        _map_result_1 = []
        for s in colors:
            id_ = f"colors:{((s if s is not None else '')).lower()}"
            _map_result_1.append((self.i18next.t(id_) if self.i18next.t(id_) is not None else id_))

        return _map_result_1
    def get_season_names(self, seasons):
        _map_result_2 = []
        for s in seasons:
            id_ = f"seasons:{((s if s is not None else '')).lower()}.season"
            _map_result_2.append((self.i18next.t(id_) if self.i18next.t(id_) is not None else id_))

        return _map_result_2
    def to_object(self):
        return _Obj({"epiphany_on_sunday": self.epiphany_on_sunday, "corpus_christi_on_sunday": self.corpus_christi_on_sunday, "ascension_on_sunday": self.ascension_on_sunday, "elevated_memorial_ids": self.elevated_memorial_ids, "locale_id": self.locale_id, "calendar_name": self.calendar_name, "easter_calculation_type": self.easter_calculation_type, "scope": self.scope, "output_options": self.output_options})
    def get(self, key, default=None):
        """Dict-style camelCase-key access for duck-type compatibility with Dates."""
        _MAP = {
            "scope":                 "scope",
            "epiphanyOnSunday":      "epiphany_on_sunday",
            "ascensionOnSunday":     "ascension_on_sunday",
            "corpusChristiOnSunday": "corpus_christi_on_sunday",
            "easterCalculationType": "easter_calculation_type",
            "elevatedMemorialIds":   "elevated_memorial_ids",
            "localeId":              "locale_id",
            "calendarName":          "calendar_name",
        }
        return getattr(self, _MAP.get(key, key), default)

