# AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
# Re-run the script to regenerate after updating the romcal TypeScript source.
# romcal version: 3.0.0-dev.125

"""
cycles_metadata.py — Python port of romcal CyclesMetadata class.

AUTO-TRANSLATED from rites/roman1969/src/models/cycles-metadata.ts.
"""

from __future__ import annotations
from datetime import date as _date, timedelta
from typing import Any

from romcal.utils.objects import _Obj
from romcal.constants import PSALTER_WEEKS, SUNDAY_CYCLES, WEEKDAY_CYCLES

class CyclesMetadata:
    proper_cycle = None
    sunday_cycle = None
    weekday_cycle = None
    psalter_week = None
    def __init__(self, d, calendar, proper_cycle, config):
        self._proper_cycle_name = None
        self._sunday_cycle_name = None
        self._weekday_cycle_name = None
        self._psalter_week_name = None
        self._config = None
        self._config = config
        year = int(calendar.start_of_liturgical_year[:4])
        if not self._config.cycles_cache[year]:
            first_sunday_of_advent = _date.fromisoformat(calendar.start_of_liturgical_year[:10])
            sunday_cycle = None
            weekday_cycle = None
            this_sunday_cycle_index = (year + 2) % 3
            next_sunday_cycle_index = (year + 3) % 3
            if d >= first_sunday_of_advent:
                sunday_cycle = SUNDAY_CYCLES[next_sunday_cycle_index]
                weekday_cycle = WEEKDAY_CYCLES[year % 2]
            else:
                sunday_cycle = SUNDAY_CYCLES[this_sunday_cycle_index]
                weekday_cycle = WEEKDAY_CYCLES[(year + 1) % 2]
            self._config.cycles_cache[year] = _Obj({"sunday_cycle": sunday_cycle, "weekday_cycle": weekday_cycle})
        week_index = (calendar.week_of_season % 4) - 1
        use_christmas_psalter_week = bool(((_date.fromisoformat(f"{year}-12-25T00:00:00.000Z"[:10]).weekday() + 1) % 7 if ("CHRISTMAS_TIME" in getattr(calendar, 'seasons', None)) else 0))
        psalter_week = PSALTER_WEEKS[((2 + calendar.week_of_season) % 4 if use_christmas_psalter_week else (week_index + 4) % 4)]
        self.proper_cycle = proper_cycle
        self.sunday_cycle = self._config.cycles_cache[year].sunday_cycle
        self.weekday_cycle = self._config.cycles_cache[year].weekday_cycle
        self.psalter_week = psalter_week
    @property
    def proper_cycle_name(self):
        if self._proper_cycle_name != None:
            return self._proper_cycle_name
        self._proper_cycle_name = self._config.i18next.t(f"cycles:{self.proper_cycle.lower()}")
        return self._proper_cycle_name
    @property
    def sunday_cycle_name(self):
        if self._sunday_cycle_name != None:
            return self._sunday_cycle_name
        self._sunday_cycle_name = self._config.i18next.t(f"cycles:sunday_{self.sunday_cycle.lower()}")
        return self._sunday_cycle_name
    @property
    def weekday_cycle_name(self):
        if self._weekday_cycle_name != None:
            return self._weekday_cycle_name
        self._weekday_cycle_name = self._config.i18next.t(f"cycles:weekday_{self.weekday_cycle.lower()}")
        return self._weekday_cycle_name
    @property
    def psalter_week_name(self):
        if self._psalter_week_name != None:
            return self._psalter_week_name
        self._psalter_week_name = self._config.i18next.t(f"cycles:psalter_{self.psalter_week.lower()}")
        return self._psalter_week_name
    def to_object(self):
        return _Obj({"proper_cycle": self.proper_cycle, "proper_cycle_name": self.proper_cycle_name, "sunday_cycle": self.sunday_cycle, "sunday_cycle_name": self.sunday_cycle_name, "weekday_cycle": self.weekday_cycle, "weekday_cycle_name": self.weekday_cycle_name, "psalter_week": self.psalter_week, "psalter_week_name": self.psalter_week_name})

