# AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
# Re-run the script to regenerate after updating the romcal TypeScript source.
# romcal version: 3.0.0-dev.125

"""
liturgical_day.py — Python port of romcal LiturgicalDay class.

AUTO-TRANSLATED from rites/roman1969/src/models/liturgical-day.ts.
"""

from __future__ import annotations

from romcal.utils.objects import _Obj
from romcal.constants import PROPER_OF_TIME_NAME
from romcal.types import MartyrologyItem
from romcal.models.cycles_metadata import CyclesMetadata
from romcal.models.liturgical_day_config import LiturgicalDayConfig
from romcal.models.liturgical_day_def import LiturgicalDayDef

COMPUTED_FIELDS = ["name", "colorNames", "seasonNames", "rankName", "definition", "config"]

class LiturgicalDay:
    id = None
    date = None
    date_def = None
    date_exceptions = None
    alternative_transfer_date_defs = None
    precedence = None
    rank = None
    allow_similar_rank_items = None
    is_holy_day_of_obligation = None
    is_optional = None
    i18n_def = None
    seasons = None
    periods = None
    colors = None
    commons_def = None
    martyrology = None
    titles = None
    calendar = None
    cycles = None
    from_calendar_id = None
    from_extended_calendars = None
    weekday = None
    @property
    def name(self):
        return self._liturgical_day_def.name
    @property
    def rank_name(self):
        return self._liturgical_day_def.rank_name
    @property
    def color_names(self):
        if self._color_names != None:
            return self._color_names
        self._color_names = self._liturgical_day_config.config.get_liturgical_color_names(self.colors)
        return self._color_names
    @property
    def season_names(self):
        if self._season_names != None:
            return self._season_names
        self._season_names = self._liturgical_day_config.config.get_season_names(self.seasons)
        return self._season_names
    @property
    def config(self):
        return self._liturgical_day_config.get_config_object()
    @property
    def definition(self):
        return self._liturgical_day_def
    def __init__(self, def_, date, liturgical_day_config, calendar, base_data, weekday):
        self._liturgical_day_def = None
        self._liturgical_day_config = None
        self._color_names = None
        self._season_names = None
        self._liturgical_day_def = def_
        self._liturgical_day_config = liturgical_day_config
        self.id = def_.id
        self.date = date.isoformat()[0:10]
        self.date_def = def_.date_def
        self.date_exceptions = def_.date_exceptions
        self.alternative_transfer_date_defs = def_.alternative_transfer_date_defs
        self.precedence = def_.precedence
        self.rank = def_.rank
        self.allow_similar_rank_items = def_.allow_similar_rank_items
        self.commons_def = def_.commons_def
        self.is_holy_day_of_obligation = (True if calendar.day_of_week == 0 else def_.is_holy_day_of_obligation)
        self.is_optional = def_.is_optional
        self.i18n_def = def_.i18n_def
        self.seasons = (getattr(base_data, 'seasons', None) if getattr(base_data, 'seasons', None) is not None else def_.seasons)
        self.periods = (getattr(base_data, 'periods', None) if getattr(base_data, 'periods', None) is not None else def_.periods)
        if def_.from_calendar_id == PROPER_OF_TIME_NAME and self.id == "second_sunday_after_christmas":
            if date >= liturgical_day_config.dates.epiphany():
                self.periods.insert(0, "DAYS_FROM_EPIPHANY")
            elif date > liturgical_day_config.dates.mary_mother_of_god():
                self.periods.insert(0, "DAYS_BEFORE_EPIPHANY")
        if def_.from_calendar_id == PROPER_OF_TIME_NAME and self.seasons[0] == "ORDINARY_TIME":
            if date < liturgical_day_config.dates.pentecost_sunday():
                self.periods.insert(0, "EARLY_ORDINARY_TIME")
            else:
                self.periods.insert(0, "LATE_ORDINARY_TIME")
        self.colors = ([] if getattr(weekday, 'precedence', None) == "PRIVILEGED_WEEKDAY_9" and (self.rank in ["MEMORIAL", "OPTIONAL_MEMORIAL"]) else def_.colors)
        self.martyrology = def_.martyrology
        self.titles = def_.titles
        self.calendar = (getattr(base_data, 'calendar', None) if getattr(base_data, 'calendar', None) is not None else calendar)
        self.cycles = CyclesMetadata(date, calendar, def_.cycles.proper_cycle, liturgical_day_config.config)
        self.from_calendar_id = def_.from_calendar_id
        self.from_extended_calendars = def_.from_extended_calendars
        if weekday:
            self.weekday = weekday
        else:
            self.weekday = None
    def to_json(self):
        temp = _Obj({**self})
        for field in COMPUTED_FIELDS:
            (temp)[field] = (self._liturgical_day_def)[field]
        return temp

