# AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
# Re-run the script to regenerate after updating the romcal TypeScript source.
# romcal version: 3.0.0-dev.125
"""
date_def.py — DateDef evaluator: compute a concrete date from a DateDef dict.

Mirrors LiturgicalDayConfig.#dateLookup and LiturgicalDayConfig.buildDate
from rites/roman1969/src/models/liturgical-day-config.ts.

DateDef variants:
  {month, date}
      → date(year + yearOffset, month, date)

  {dateFn, dateArgs?, addDay?, subtractDay?, yearOffset?}
      → call dates.date_fn(*dateArgs, year + yearOffset)
         then optionally add/subtract days

  {month, dayOfWeek, nthWeekInMonth}
      → Nth occurrence of dayOfWeek in month

  {month, lastDayOfWeekInMonth}
      → last occurrence of dayOfWeek in month

DateException variants (applied in order to override the computed date):
  {ifIsBetween: {from, to, inclusive}, setDate}
  {ifIsSameAsDate: DateDef, setDate}
  {ifIsDayOfWeek: int, setDate}
"""

from __future__ import annotations
import calendar as _cal
from datetime import date as _date, timedelta
from typing import Any
from romcal.utils.objects import _Obj
from romcal.utils.dates import Dates, add_days, days_in_month, get_utc_date, is_same_date, is_valid_date, subtracts_days
from romcal.utils.numbers import is_integer
from romcal.models.config import RomcalConfig
from romcal.models.liturgical_day_def import LiturgicalDayDef



def _days_in_month(d: date) -> int:
    """Number of days in the month of date d."""
    return _cal.monthrange(d.year, d.month)[1]


def _get_next_dow(d: date, dow: int) -> date:
    """
    Return the next occurrence of day-of-week dow on or after date d.
    dow: 0=Sunday, 1=Monday, ..., 6=Saturday  (JS/UTC convention).
    Python weekday(): 0=Monday … 6=Sunday → convert.
    """
    # JS dow 0=Sun, Python isoweekday 7=Sun → JS_dow = isoweekday % 7
    js_dow_of_d = d.isoweekday() % 7
    delta = (7 + dow - js_dow_of_d) % 7
    return d + timedelta(days=delta)


def _date_lookup(
    date_def: Any,
    year: int,
    dates_obj: Any,
    year_offset: int = 0,
) -> date | None:
    """
    Compute a concrete date from a DateDef dict or _Obj.

    :param date_def:   The DateDef dict or _Obj.  Keys may be camelCase (bundle
                       JSON) or snake_case (ProperOfTime entries from translator).
                       If date_def is an _Obj, attribute access tries snake_case
                       first then camelCase automatically; if it is a plain dict,
                       we try both keys manually.
    :param year:       Base year (LiturgicalDayConfig.year).
    :param dates_obj:  A Dates-compatible object whose methods can be called.
    :param year_offset: Additional year offset (for liturgical scope lookback.
    :returns:          A date, or None if not computable.
    """
    # All date_def objects are _Obj instances with snake_case keys, normalised
    # by _deep_ns() at load time.  Simple dict.get() with snake_case keys works.
    effective_year = year + (date_def.get("year_offset") or 0) + year_offset
    result: date | None = None

    month = date_def.get("month")
    day   = date_def.get("date")
    date_fn      = date_def.get("date_fn")
    date_args    = date_def.get("date_args") or []
    add_day      = date_def.get("add_day")
    subtract_day = date_def.get("subtract_day")
    dow          = date_def.get("day_of_week")
    nth_week     = date_def.get("nth_week_in_month")
    last_dow     = date_def.get("last_day_of_week_in_month")

    if isinstance(month, int) and isinstance(day, int) and month > 0 and day > 0:
        # DateDefMonthDate
        try:
            result = _date(effective_year, month, day)
        except ValueError:
            return None

    elif isinstance(date_fn, str) and hasattr(dates_obj, _snake(date_fn)):
        # DateDefDateFnAddDay / DateDefDateFnSubtractDay
        fn = getattr(dates_obj, _snake(date_fn))
        args = list(date_args) + [effective_year]
        try:
            raw = fn(*args)
        except Exception:
            return None
        if isinstance(raw, list):
            raw = next((r for r in raw if r is not None), None)
        if not isinstance(raw, _date):
            return None
        result = raw
        if isinstance(add_day, int):
            result = result + timedelta(days=add_day)
        if isinstance(subtract_day, int):
            result = result - timedelta(days=subtract_day)

    elif isinstance(month, int) and isinstance(dow, int) and isinstance(nth_week, int):
        # DateDefMonthDowNthWeekInMonth
        # First day of the 7-day block containing the nth occurrence
        try:
            first_of_block = _date(effective_year, month, 7 * nth_week - 6)
        except ValueError:
            return None
        result = _get_next_dow(first_of_block, dow)

    elif isinstance(month, int) and isinstance(last_dow, int):
        # DateDefMonthLastDowInMonth
        try:
            first = _date(effective_year, month, 1)
        except ValueError:
            return None
        days = _days_in_month(first)
        last_day = _date(effective_year, month, days)
        # Start of the last 7-day block
        first_of_last_block = last_day - timedelta(days=6)
        result = _get_next_dow(first_of_last_block, last_dow)

    return result


def _snake(name: str) -> str:
    """camelCase → snake_case (minimal version for dateFn strings)."""
    import re
    s = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    return re.sub(r"([a-z\d])([A-Z])", r"\1_\2", s).lower()


def _set_date(
    original: date,
    date_def_extended: dict[str, Any],
    year: int,
    dates_obj: Any,
    year_offset: int,
) -> date | None:
    """Apply a setDate override dict to produce a new date."""
    add = date_def_extended.get("add_day")
    sub = date_def_extended.get("subtract_day")
    if isinstance(add, int):
        return original + timedelta(days=add)
    if isinstance(sub, int):
        return original - timedelta(days=sub)
    # Otherwise it's a full DateDef
    return _date_lookup(date_def_extended, year, dates_obj, year_offset)


def build_date(
    def_obj: Any,
    year: int,
    dates_obj: Any,
    year_offset: int = 0,
) -> date | None:
    """
    Compute the concrete date for a liturgical day definition, applying
    any date exceptions.

    :param def_obj:    Object or dict with ``dateDef`` and ``dateExceptions``.
    :param year:       Base year.
    :param dates_obj:  Dates helper (must have camelCase methods).
    :param year_offset: Offset for liturgical scope lookback.
    :returns:          Resolved date, or None.
    """
    # All objects are _Obj with snake_case keys (normalised by _deep_ns at load time).
    # LiturgicalDayDef stores date_def and date_exceptions as attributes.
    date_def       = getattr(def_obj, "date_def", None) or {}
    date_exceptions = getattr(def_obj, "date_exceptions", None) or []

    computed = _date_lookup(date_def, year, dates_obj, year_offset)
    if computed is None:
        return None

    updated = computed

    for exc in date_exceptions:
        if not isinstance(exc, (dict, _Obj)):
            continue

        if_between   = exc.get("if_is_between")
        if_same      = exc.get("if_is_same_as_date")
        if_dow       = exc.get("if_is_day_of_week")
        set_date_def = exc.get("set_date") or {}

        if isinstance(if_between, dict):
            from_d = _date_lookup(if_between.get("from") or {}, year, dates_obj, year_offset)
            to_d   = _date_lookup(if_between.get("to")   or {}, year, dates_obj, year_offset)
            if from_d and to_d:
                inclusive = if_between.get("inclusive", False)
                if inclusive:
                    in_range = from_d <= computed <= to_d
                else:
                    in_range = from_d < computed < to_d
                if in_range:
                    updated = _set_date(computed, set_date_def, year, dates_obj, year_offset) or updated

        elif isinstance(if_same, dict):
            cmp_d = _date_lookup(if_same, year, dates_obj, year_offset)
            if cmp_d and cmp_d == computed:
                updated = _set_date(computed, set_date_def, year, dates_obj, year_offset) or updated

        elif isinstance(if_dow, int):
            js_dow = computed.isoweekday() % 7  # 0=Sun, 1=Mon, ..., 6=Sat
            if js_dow == if_dow:
                updated = _set_date(computed, set_date_def, year, dates_obj, year_offset) or updated

    return updated

class LiturgicalDayConfig:
    """
    Python port of romcal LiturgicalDayConfig.

    Wraps a RomcalConfig and a specific year, providing build_date()
    to resolve DateDef objects to concrete Python date objects.

    TS: rites/roman1969/src/models/liturgical-day-config.ts
    """

    def __init__(self, config, year=None):
        self.config = config
        current_year = _date.today().year
        current_liturgical_year = (current_year if _date.today() < Dates.first_sunday_of_advent(current_year + 1) else current_year + 1)
        self.year = (year if year is not None else ((current_year if config.scope == "gregorian" else current_liturgical_year)))
        self.dates = Dates(config, self.year)
    def _date_lookup(self, date_def: Any, year_offset: int = 0) -> "date | None":
        """
        Delegates to the standalone _date_lookup() helper above, passing
        self.year and self.dates as context.

        The TS #dateLookup private method uses attribute access on dateDef
        (JS typed objects), which can't be directly translated when dateDef
        is a Python dict.  The standalone _date_lookup() handles both dicts
        and namespace objects.
        """
        return _date_lookup(date_def, self.year, self.dates, year_offset)

    def build_date(self, def_obj: Any, year_offset: int = 0) -> "date | None":
        """
        Compute the concrete date for a liturgical day definition.

        Mirrors LiturgicalDayConfig.buildDate() in TS.
        Delegates to the standalone build_date() helper above.
        """
        return build_date(def_obj, self.year, self.dates, year_offset)
