# AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
# Re-run the script to regenerate after updating the romcal TypeScript source.
# romcal version: 3.0.0-dev.125

"""
utils/arrays.py — Python port of romcal utils/arrays.ts.

AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
"""

from __future__ import annotations

def safe_wrap_array(input_=None, fallback=None):
    if isinstance(input_, list):
        return input_
    return ([input_] if input_ else fallback)

