# AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
# Re-run the script to regenerate after updating the romcal TypeScript source.
# romcal version: 3.0.0-dev.125

"""
utils/dates.py — Python port of romcal utils/dates.ts.

Provides the Dates class and utility functions for all liturgical
date calculations (Easter, moveable feasts, seasons, Lunar New Year).

AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
"""

from __future__ import annotations

import functools
from datetime import date as _date, timedelta
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from romcal.models.config import RomcalConfig

from romcal.utils.objects import _Obj
from romcal.utils.easter import calculate_gregorian_easter_date, calculate_julian_easter_date_to_gregorian_date
from romcal.utils.lunar_new_year import calculate_lunar_new_year

def get_utc_date(year, month, date):
    return _date(int(year), int((month - 1) + 1), int(date))

def get_utc_date_from_string(date_str):
    year, month, date = [int(n[:4]) for n in date_str.split("-")]
    return _date(year, month, date)

def add_days(date, days):
    return _date.fromisoformat(date.value_of() + 864e5 * days[:10])

def subtracts_days(date, days):
    return _date.fromisoformat(date.value_of() - 864e5 * days[:10])

def is_same_date(date1, date2):
    return (date1.year == date2.year and (date1.month - 1) == (date2.month - 1) and date1.day == date2.day)

def date_difference(date1, date2):
    return abs(int((date2 - date1) // (1000 * 60 * 60 * 24)))

def start_of_week(date):
    return (date - timedelta(days=(date.weekday() + 1) % 7))

def is_valid_date(maybe_date):
    if maybe_date and "[object Date]" == "[object Date]":
        if False:
            return False
        return True
    return False

def days_in_month(date):
    return _date(int(date.year), int(((date.month - 1) + 1) + 1), int(0)).day

def get_week_number(date):
    d = _date(int(date.year), int(((date.month - 1)) + 1), int(date.day))
    d = d.replace(day=d.day + 4 - ((d.weekday() + 1) % 7 or 7))
    return -(-(((d - _date(int(d.year), int((0) + 1), int(1))) / 864e5 + 1)) // (7))

def range_of_days(start, end):
    days = abs((end) - (start)).days
    _array_from_1 = []
    for i in range(days + 1):
        _array_from_1.append((start + timedelta(days=i)))

    return _array_from_1

def range_contains_date(range_, date):
    return (date.isoformat() in [d.isoformat() for d in range_])


def _indexed_reduce(fn, items, initial=None):
    """Like functools.reduce but passes (acc, item, idx) to fn."""
    result = initial
    for idx, item in enumerate(items):
        result = fn(result, item, idx) if result is not None else item
    return result

class Dates:
    def __init__(self, config, year):
        self._config = None
        self._year = None
        self._is_liturgical_year = None
        self._all_dates_of_advent = _Obj({})
        self._all_sundays_of_advent = _Obj({})
        self._first_sunday_of_advent = _Obj({})
        self._unprivileged_weekday_of_advent = _Obj({})
        self._privileged_weekday_of_advent = _Obj({})
        self._sunday_of_advent = _Obj({})
        self._christmas = _Obj({})
        self._all_dates_in_octave_of_christmas = _Obj({})
        self._weekday_within_octave_of_christmas = _Obj({})
        self._all_dates_of_christmas_time = _Obj({})
        self._second_sunday_after_christmas = _Obj({})
        self._all_dates_before_epiphany = _Obj({})
        self._weekday_before_epiphany = _Obj({})
        self._epiphany = _Obj({})
        self._all_dates_after_epiphany = _Obj({})
        self._weekday_after_epiphany = _Obj({})
        self._ash_wednesday = _Obj({})
        self._all_sundays_of_lent = _Obj({})
        self._all_dates_of_lent = _Obj({})
        self._palm_sunday = _Obj({})
        self._holy_thursday = _Obj({})
        self._good_friday = _Obj({})
        self._holy_saturday = _Obj({})
        self._all_dates_of_holy_week = _Obj({})
        self._all_dates_of_paschal_triduum = _Obj({})
        self._easter = _Obj({})
        self._all_dates_in_octave_of_easter = _Obj({})
        self._all_sundays_of_easter = _Obj({})
        self._weekday_or_sunday_of_easter_time = _Obj({})
        self._all_dates_of_easter_time = _Obj({})
        self._divine_mercy_sunday = _Obj({})
        self._pentecost_sunday = _Obj({})
        self._all_dates_of_ordinary_time = _Obj({})
        self._all_dates_of_early_ordinary_time = _Obj({})
        self._sundays_of_early_ordinary_time = _Obj({})
        self._all_dates_of_late_ordinary_time = _Obj({})
        self._all_sundays_of_late_ordinary_time = _Obj({})
        self._christ_the_king_sunday = _Obj({})
        self._date_of_ordinary_time = _Obj({})
        self._mary_mother_of_god = _Obj({})
        self._annunciation = _Obj({})
        self._nativity_of_john_the_baptist = _Obj({})
        self._peter_and_paul_apostles = _Obj({})
        self._assumption = _Obj({})
        self._all_saints = _Obj({})
        self._immaculate_conception_of_mary = _Obj({})
        self._ascension = _Obj({})
        self._mary_mother_of_the_church = _Obj({})
        self._trinity_sunday = _Obj({})
        self._corpus_christi = _Obj({})
        self._most_sacred_heart_of_jesus = _Obj({})
        self._immaculate_heart_of_mary = _Obj({})
        self._holy_family = _Obj({})
        self._baptism_of_the_lord = _Obj({})
        self._presentation_of_the_lord = _Obj({})
        self._transfiguration = _Obj({})
        self._exaltation_of_the_holy_cross = _Obj({})
        self._lunar_new_year = _Obj({})
        self._sunday_on_or_after_lunar_new_year = _Obj({})
        self._start_of_seasons = _Obj({})
        self._end_of_seasons = _Obj({})
        self._config = config
        self._year = year
        self._is_liturgical_year = self._config.scope == "liturgical"
    def all_dates_of_advent(self, year=None):
        if year is None: year = (self._year - 1 if self._is_liturgical_year else self._year)
        if self._all_dates_of_advent[year]:
            return self._all_dates_of_advent[year]
        start = self.first_sunday_of_advent(year)
        end = (self.christmas(year) - timedelta(days=1))
        self._all_dates_of_advent[year] = range_of_days(start, end)
        return self._all_dates_of_advent[year]
    def all_sundays_of_advent(self, year=None):
        if year is None: year = (self._year - 1 if self._is_liturgical_year else self._year)
        if self._all_sundays_of_advent[year]:
            return self._all_sundays_of_advent[year]
        first_sunday = self.first_sunday_of_advent(year)
        self._all_sundays_of_advent[year] = [first_sunday, (first_sunday + timedelta(days=7)), (first_sunday + timedelta(days=14)), (first_sunday + timedelta(days=21))]
        return self._all_sundays_of_advent[year]
    def first_sunday_of_advent(self_or_year, _p1=None):
        if isinstance(self_or_year, Dates):
            self = self_or_year
            year = _p1
            if year is None: year = (self._year - 1 if self._is_liturgical_year else self._year)
            if self._first_sunday_of_advent[year]:
                return self._first_sunday_of_advent[year]
            self._first_sunday_of_advent[year] = Dates.first_sunday_of_advent(year)
            return self._first_sunday_of_advent[year]
        else:
            year = self_or_year
            if ((Dates.christmas(year).weekday() + 1) % 7) == 0:
                return _date(year, 11, 27)
            elif ((Dates.christmas(year).weekday() + 1) % 7) == 1:
                return _date(year, 12, 3)
            elif ((Dates.christmas(year).weekday() + 1) % 7) == 2:
                return _date(year, 12, 2)
            elif ((Dates.christmas(year).weekday() + 1) % 7) == 3:
                return _date(year, 12, 1)
            elif ((Dates.christmas(year).weekday() + 1) % 7) == 4:
                return _date(year, 11, 30)
            elif ((Dates.christmas(year).weekday() + 1) % 7) == 5:
                return _date(year, 11, 29)
            else:
                return _date(year, 11, 28)
    def unprivileged_weekday_of_advent(self, dow, week, year=None):
        if year is None: year = (self._year - 1 if self._is_liturgical_year else self._year)
        id_ = f"{year}_{week}_{dow}"
        if self._unprivileged_weekday_of_advent[id_] != None:
            return self._unprivileged_weekday_of_advent[id_]
        if dow < 1 or dow > 6 or week < 1 or week > 4:
            self._unprivileged_weekday_of_advent[id_] = None
            return self._unprivileged_weekday_of_advent[id_]
        date = (self.first_sunday_of_advent(year) + timedelta(days=(week - 1) * 7 + dow))
        if date.day >= 17 and (date.month - 1) == 11 and (date.weekday() + 1) % 7 != 0:
            date = None
        self._unprivileged_weekday_of_advent[id_] = date
        return self._unprivileged_weekday_of_advent[id_]
    def privileged_weekday_of_advent(self, day, year=None):
        if year is None: year = (self._year - 1 if self._is_liturgical_year else self._year)
        id_ = f"{year}_{day}"
        if self._privileged_weekday_of_advent[id_] != None:
            return self._privileged_weekday_of_advent[id_]
        if day < 17 or day > 24:
            self._privileged_weekday_of_advent[id_] = None
            return self._privileged_weekday_of_advent[id_]
        date = _date(year, 12, day)
        if (date.weekday() + 1) % 7 == 0:
            date = None
        self._privileged_weekday_of_advent[id_] = date
        return self._privileged_weekday_of_advent[id_]
    def sunday_of_advent(self, week, year=None):
        if year is None: year = (self._year - 1 if self._is_liturgical_year else self._year)
        id_ = f"{year}_{week}"
        if self._sunday_of_advent[id_] != None:
            return self._sunday_of_advent[id_]
        if week < 1 or week > 4:
            self._sunday_of_advent[id_] = None
            return self._sunday_of_advent[id_]
        self._sunday_of_advent[id_] = (self.first_sunday_of_advent(year) + timedelta(days=7 * (week - 1)))
        return self._sunday_of_advent[id_]
    def christmas(self_or_year, _p1=None):
        if isinstance(self_or_year, Dates):
            self = self_or_year
            year = _p1
            if year is None: year = (self._year - 1 if self._is_liturgical_year else self._year)
            if self._christmas[year]:
                return self._christmas[year]
            self._christmas[year] = Dates.christmas(year)
            return self._christmas[year]
        else:
            year = self_or_year
            return _date(year, 12, 25)
    def all_dates_in_octave_of_christmas(self, year=None):
        if year is None: year = (self._year - 1 if self._is_liturgical_year else self._year)
        if self._all_dates_in_octave_of_christmas[year]:
            return self._all_dates_in_octave_of_christmas[year]
        self._all_dates_in_octave_of_christmas[year] = (range_of_days(self.christmas(year), (self.christmas(year) + timedelta(days=6))) + (lambda _c: _c if isinstance(_c, list) else [_c])(self.mary_mother_of_god(year)))
        return self._all_dates_in_octave_of_christmas[year]
    def weekday_within_octave_of_christmas(self, day_of_octave, year=None):
        if year is None: year = (self._year - 1 if self._is_liturgical_year else self._year)
        id_ = f"{year}_{day_of_octave}"
        if self._weekday_within_octave_of_christmas[id_] != None:
            return self._weekday_within_octave_of_christmas[id_]
        if day_of_octave < 1 or day_of_octave > 8:
            self._weekday_within_octave_of_christmas[id_] = None
            return self._weekday_within_octave_of_christmas[id_]
        date = (self.christmas(year) + timedelta(days=day_of_octave - 1))
        if (date == self.holy_family(year)):
            date = None
        self._weekday_within_octave_of_christmas[id_] = date
        return self._weekday_within_octave_of_christmas[id_]
    def all_dates_of_christmas_time(self, year=None, epiphany_on_sunday=None):
        if year is None: year = (self._year - 1 if self._is_liturgical_year else self._year)
        if epiphany_on_sunday is None: epiphany_on_sunday = self._config.epiphany_on_sunday
        id_ = str(year) + str(epiphany_on_sunday)
        if self._all_dates_of_christmas_time[id_]:
            return self._all_dates_of_christmas_time[id_]
        start = self.christmas(year)
        end = self.baptism_of_the_lord(year + 1, epiphany_on_sunday)
        self._all_dates_of_christmas_time[id_] = range_of_days(start, end)
        return self._all_dates_of_christmas_time[id_]
    def second_sunday_after_christmas(self, year=None, epiphany_on_sunday=None):
        if year is None: year = self._year
        if epiphany_on_sunday is None: epiphany_on_sunday = self._config.epiphany_on_sunday
        id_ = str(year) + str(epiphany_on_sunday)
        if self._second_sunday_after_christmas[id_] != None:
            return self._second_sunday_after_christmas[id_]
        if epiphany_on_sunday:
            self._second_sunday_after_christmas[id_] = None
            return self._second_sunday_after_christmas[id_]
        date = (next((d for d in self.all_dates_before_epiphany(year, epiphany_on_sunday) if (d.weekday() + 1) % 7 == 0), None) if next((d for d in self.all_dates_before_epiphany(year, epiphany_on_sunday) if (d.weekday() + 1) % 7 == 0), None) is not None else next((d for d in self.all_dates_after_epiphany(year, epiphany_on_sunday) if (d.weekday() + 1) % 7 == 0), None))
        self._second_sunday_after_christmas[id_] = (date if date is not None else None)
        return self._second_sunday_after_christmas[id_]
    def all_dates_before_epiphany(self, year=None, epiphany_on_sunday=None):
        if year is None: year = self._year
        if epiphany_on_sunday is None: epiphany_on_sunday = self._config.epiphany_on_sunday
        id_ = str(year) + str(epiphany_on_sunday)
        if self._all_dates_before_epiphany[id_]:
            return self._all_dates_before_epiphany[id_]
        start = (self.mary_mother_of_god(year) + timedelta(days=1))
        epiphany = self.epiphany(year, epiphany_on_sunday)
        if (start == epiphany):
            self._all_dates_before_epiphany[id_] = []
            return self._all_dates_before_epiphany[id_]
        end = (epiphany - timedelta(days=1))
        self._all_dates_before_epiphany[id_] = range_of_days(start, end)
        return self._all_dates_before_epiphany[id_]
    def weekday_before_epiphany(self, day, year=None, epiphany_on_sunday=None):
        if year is None: year = self._year
        if epiphany_on_sunday is None: epiphany_on_sunday = self._config.epiphany_on_sunday
        id_ = f"{day}_{year}_{str(epiphany_on_sunday)}"
        if self._weekday_before_epiphany[id_] != None:
            return self._weekday_before_epiphany[id_]
        if day < 2 or day > 8:
            self._weekday_before_epiphany[id_] = None
            return self._weekday_before_epiphany[id_]
        self._weekday_before_epiphany[id_] = (next((d for d in self.all_dates_before_epiphany(year, epiphany_on_sunday) if d.day == day), None) if next((d for d in self.all_dates_before_epiphany(year, epiphany_on_sunday) if d.day == day), None) is not None else None)
        return self._weekday_before_epiphany[id_]
    def epiphany(self, year=None, epiphany_on_sunday=None):
        if year is None: year = self._year
        if epiphany_on_sunday is None: epiphany_on_sunday = self._config.epiphany_on_sunday
        id_ = str(year) + str(epiphany_on_sunday)
        if self._epiphany[id_]:
            return self._epiphany[id_]
        first_day = _date(year, 1, 1)
        date = _date(year, 1, 6)
        if epiphany_on_sunday:
            if ((first_day.weekday() + 1) % 7) == 6:
                date = (first_day + timedelta(days=1))
                # TS: break;
            elif ((first_day.weekday() + 1) % 7) == 0:
                date = (first_day + timedelta(days=7))
                # TS: break;
            else:
                date = start_of_week((first_day + timedelta(days=7)))
                # TS: break;
        self._epiphany[id_] = date
        return self._epiphany[id_]
    def all_dates_after_epiphany(self, year=None, epiphany_on_sunday=None):
        if year is None: year = self._year
        if epiphany_on_sunday is None: epiphany_on_sunday = self._config.epiphany_on_sunday
        id_ = str(year) + str(epiphany_on_sunday)
        if self._all_dates_after_epiphany[id_]:
            return self._all_dates_after_epiphany[id_]
        start = (self.epiphany(year, epiphany_on_sunday) + timedelta(days=1))
        baptism_of_the_lord = self.baptism_of_the_lord(year, epiphany_on_sunday)
        if (start == baptism_of_the_lord):
            self._all_dates_after_epiphany[id_] = []
            return self._all_dates_after_epiphany[id_]
        end = (baptism_of_the_lord - timedelta(days=1))
        self._all_dates_after_epiphany[id_] = range_of_days(start, end)
        return self._all_dates_after_epiphany[id_]
    def weekday_after_epiphany(self, dow, year=None, epiphany_on_sunday=None):
        if year is None: year = self._year
        if epiphany_on_sunday is None: epiphany_on_sunday = self._config.epiphany_on_sunday
        id_ = f"{dow}_{year}_{str(epiphany_on_sunday)}"
        if self._weekday_after_epiphany[id_] != None:
            return self._weekday_after_epiphany[id_]
        if dow < 1 or dow > 6:
            self._weekday_after_epiphany[id_] = None
            return self._weekday_after_epiphany[id_]
        self._weekday_after_epiphany[id_] = (next((d for d in self.all_dates_after_epiphany(year, epiphany_on_sunday) if (d.weekday() + 1) % 7 == dow), None) if next((d for d in self.all_dates_after_epiphany(year, epiphany_on_sunday) if (d.weekday() + 1) % 7 == dow), None) is not None else None)
        return self._weekday_after_epiphany[id_]
    def ash_wednesday(self, year=None):
        if year is None: year = self._year
        if self._ash_wednesday[year]:
            return self._ash_wednesday[year]
        self._ash_wednesday[year] = (self.easter_sunday(year) - timedelta(days=46))
        return self._ash_wednesday[year]
    def all_sundays_of_lent(self, year=None):
        if year is None: year = self._year
        if self._all_sundays_of_lent[year]:
            return self._all_sundays_of_lent[year]
        first_sunday = (self.ash_wednesday(year) + timedelta(days=4))
        self._all_sundays_of_lent[year] = [first_sunday, (first_sunday + timedelta(days=7)), (first_sunday + timedelta(days=14)), (first_sunday + timedelta(days=21)), (first_sunday + timedelta(days=28)), (first_sunday + timedelta(days=35))]
        return self._all_sundays_of_lent[year]
    def all_dates_of_lent(self, year=None):
        if year is None: year = self._year
        if self._all_dates_of_lent[year]:
            return self._all_dates_of_lent[year]
        start = self.ash_wednesday(year)
        end = self.holy_thursday(year)
        self._all_dates_of_lent[year] = range_of_days(start, end)
        return self._all_dates_of_lent[year]
    def palm_sunday(self, year=None):
        if year is None: year = self._year
        if self._palm_sunday[year]:
            return self._palm_sunday[year]
        self._palm_sunday[year] = (self.easter_sunday(year) - timedelta(days=7))
        return self._palm_sunday[year]
    def holy_thursday(self, year=None):
        if year is None: year = self._year
        if self._holy_thursday[year]:
            return self._holy_thursday[year]
        self._holy_thursday[year] = (self.easter_sunday(year) - timedelta(days=3))
        return self._holy_thursday[year]
    def good_friday(self, year=None):
        if year is None: year = self._year
        if self._good_friday[year]:
            return self._good_friday[year]
        self._good_friday[year] = (self.easter_sunday(year) - timedelta(days=2))
        return self._good_friday[year]
    def holy_saturday(self, year=None):
        if year is None: year = self._year
        if self._holy_saturday[year]:
            return self._holy_saturday[year]
        self._holy_saturday[year] = (self.easter_sunday(year) - timedelta(days=1))
        return self._holy_saturday[year]
    def all_dates_of_holy_week(self, year=None):
        if year is None: year = self._year
        if self._all_dates_of_holy_week[year]:
            return self._all_dates_of_holy_week[year]
        start = self.palm_sunday(year)
        end = self.holy_saturday(year)
        self._all_dates_of_holy_week[year] = range_of_days(start, end)
        return self._all_dates_of_holy_week[year]
    def all_dates_of_paschal_triduum(self, year=None):
        if year is None: year = self._year
        if self._all_dates_of_paschal_triduum[year]:
            return self._all_dates_of_paschal_triduum[year]
        start = self.holy_thursday(year)
        end = self.easter_sunday(year)
        self._all_dates_of_paschal_triduum[year] = range_of_days(start, end)
        return self._all_dates_of_paschal_triduum[year]
    def easter_sunday(self, year=None, easter_calculation_type=None):
        if year is None: year = self._year
        if easter_calculation_type is None: easter_calculation_type = self._config.easter_calculation_type
        if self._easter[year]:
            return self._easter[year]
        _tmp_0 = (calculate_gregorian_easter_date(year) if easter_calculation_type == "gregorian" else calculate_julian_easter_date_to_gregorian_date(year))
        day = _tmp_0.day
        month = _tmp_0.month
        self._easter[year] = _date(year, month, day)
        return self._easter[year]
    def all_dates_in_octave_of_easter(self, year=None):
        if year is None: year = self._year
        if self._all_dates_in_octave_of_easter[year]:
            return self._all_dates_in_octave_of_easter[year]
        start = self.easter_sunday(year)
        end = self.divine_mercy_sunday(year)
        self._all_dates_in_octave_of_easter[year] = range_of_days(start, end)
        return self._all_dates_in_octave_of_easter[year]
    def all_sundays_of_easter(self, year=None):
        if year is None: year = self._year
        if self._all_sundays_of_easter[year]:
            return self._all_sundays_of_easter[year]
        first_sunday = self.easter_sunday(year)
        self._all_sundays_of_easter[year] = [first_sunday, (first_sunday + timedelta(days=7)), (first_sunday + timedelta(days=14)), (first_sunday + timedelta(days=21)), (first_sunday + timedelta(days=28)), (first_sunday + timedelta(days=35)), (first_sunday + timedelta(days=42)), (first_sunday + timedelta(days=49))]
        return self._all_sundays_of_easter[year]
    def weekday_or_sunday_of_easter_time(self, dow, week, year=None, ascension_on_sunday=None):
        if year is None: year = self._year
        if ascension_on_sunday is None: ascension_on_sunday = self._config.ascension_on_sunday
        id_ = f"{year}_{ascension_on_sunday}_{week}_{dow}"
        if self._weekday_or_sunday_of_easter_time[id_] != None:
            return self._weekday_or_sunday_of_easter_time[id_]
        if week < 1 or week > 7 or dow < 0 or dow > 6:
            self._weekday_or_sunday_of_easter_time[id_] = None
            return self._weekday_or_sunday_of_easter_time[id_]
        date = (self.easter_sunday(year) + timedelta(days=(week - 1) * 7 + dow))
        ascension = self.ascension(year, ascension_on_sunday)
        self._weekday_or_sunday_of_easter_time[id_] = (None if (ascension == date) else date)
        return self._weekday_or_sunday_of_easter_time[id_]
    def all_dates_of_easter_time(self, year=None):
        if year is None: year = self._year
        if self._all_dates_of_easter_time[year]:
            return self._all_dates_of_easter_time[year]
        start = self.easter_sunday(year)
        end = self.pentecost_sunday(year)
        self._all_dates_of_easter_time[year] = range_of_days(start, end)
        return self._all_dates_of_easter_time[year]
    def divine_mercy_sunday(self, year=None):
        if year is None: year = self._year
        if self._divine_mercy_sunday[year]:
            return self._divine_mercy_sunday[year]
        self._divine_mercy_sunday[year] = (self.easter_sunday(year) + timedelta(days=7))
        return self._divine_mercy_sunday[year]
    def pentecost_sunday(self, year=None):
        if year is None: year = self._year
        if self._pentecost_sunday[year]:
            return self._pentecost_sunday[year]
        self._pentecost_sunday[year] = (self.easter_sunday(year) + timedelta(days=49))
        return self._pentecost_sunday[year]
    def all_dates_of_ordinary_time(self, year=None, epiphany_on_sunday=None):
        if year is None: year = self._year
        if epiphany_on_sunday is None: epiphany_on_sunday = self._config.epiphany_on_sunday
        id_ = str(year) + str(epiphany_on_sunday)
        if self._all_dates_of_ordinary_time[id_]:
            return self._all_dates_of_ordinary_time[id_]
        self._all_dates_of_ordinary_time[id_] = [*self.all_dates_of_early_ordinary_time(year, epiphany_on_sunday), *self.all_dates_of_late_ordinary_time(year)]
        return self._all_dates_of_ordinary_time[id_]
    def all_dates_of_early_ordinary_time(self, year=None, epiphany_on_sunday=None):
        if year is None: year = self._year
        if epiphany_on_sunday is None: epiphany_on_sunday = self._config.epiphany_on_sunday
        id_ = str(year) + str(epiphany_on_sunday)
        if self._all_dates_of_early_ordinary_time[id_]:
            return self._all_dates_of_early_ordinary_time[id_]
        start = (self.baptism_of_the_lord(year, epiphany_on_sunday) + timedelta(days=1))
        end = (self.ash_wednesday(year) - timedelta(days=1))
        self._all_dates_of_early_ordinary_time[id_] = range_of_days(start, end)
        return self._all_dates_of_early_ordinary_time[id_]
    def sundays_of_early_ordinary_time(self, year=None):
        if year is None: year = self._year
        if self._sundays_of_early_ordinary_time[year]:
            return self._sundays_of_early_ordinary_time[year]
        self._sundays_of_early_ordinary_time[year] = [d for d in self.all_dates_of_early_ordinary_time(year) if (d.weekday() + 1) % 7 == 0]
        return self._sundays_of_early_ordinary_time[year]
    def all_dates_of_late_ordinary_time(self, year=None):
        if year is None: year = self._year
        if self._all_dates_of_late_ordinary_time[year]:
            return self._all_dates_of_late_ordinary_time[year]
        start = (self.pentecost_sunday(year) + timedelta(days=1))
        end = (self.first_sunday_of_advent(year) - timedelta(days=1))
        self._all_dates_of_late_ordinary_time[year] = range_of_days(start, end)
        return self._all_dates_of_late_ordinary_time[year]
    def all_sundays_of_late_ordinary_time(self, year=None):
        if year is None: year = self._year
        if self._all_sundays_of_late_ordinary_time[year]:
            return self._all_sundays_of_late_ordinary_time[year]
        self._all_sundays_of_late_ordinary_time[year] = [d for d in self.all_dates_of_late_ordinary_time(year) if (d.weekday() + 1) % 7 == 0]
        return self._all_sundays_of_late_ordinary_time[year]
    def christ_the_king_sunday(self, year=None):
        if year is None: year = self._year
        if self._christ_the_king_sunday[year]:
            return self._christ_the_king_sunday[year]
        self._christ_the_king_sunday[year] = (self.first_sunday_of_advent(year) - timedelta(days=7))
        return self._christ_the_king_sunday[year]
    def date_of_ordinary_time(self, dow, week, year=None, epiphany_on_sunday=None):
        if year is None: year = self._year
        if epiphany_on_sunday is None: epiphany_on_sunday = self._config.epiphany_on_sunday
        id_ = str(year) + str(epiphany_on_sunday)
        if self._date_of_ordinary_time[id_] == None:
            early = self.all_dates_of_early_ordinary_time(year, epiphany_on_sunday)
            late = self.all_dates_of_late_ordinary_time(year)
            late_ordinary_start_week_count = int(35 - (len(late) + 1) / 7)
            baptism_of_the_lord_is_monday = (self.baptism_of_the_lord(year).weekday() + 1) % 7 == 1
            trinity_sunday = self.trinity_sunday(year)
            corpus_christi = self.corpus_christi(year)
            most_sacred_heart_of_jesus = self.most_sacred_heart_of_jesus(year)
            def group_by(dates, is_early_ordinary_time):
                def _reduce_fn_2(result, item, idx):
                    late_ordinary_time = (late_ordinary_start_week_count + int(idx // 7) + 1 if (item.weekday() + 1) % 7 == 0 else late_ordinary_start_week_count + int(idx // 7))
                    early_ordinary_time = (int(idx // 7) + 2 if (item.weekday() + 1) % 7 == 0 else int(idx // 7) + 1)
                    week_number = (early_ordinary_time if is_early_ordinary_time else late_ordinary_time)
                    if is_early_ordinary_time and baptism_of_the_lord_is_monday and (item.weekday() + 1) % 7 == 1:
                        week_number += 1
                    date_time = item
                    date = (None if date_time == trinity_sunday or date_time == corpus_christi or date_time == most_sacred_heart_of_jesus else item)
                    return _Obj({**result, week_number: _Obj({**(result[week_number] or {}), (item.weekday() + 1) % 7: date})})

                return _indexed_reduce(_reduce_fn_2, dates, _Obj({}))
            self._date_of_ordinary_time[id_] = _Obj({**group_by(early, True), **group_by(late, False)})
        return (self._date_of_ordinary_time[id_][week][dow] if self._date_of_ordinary_time[id_][week][dow] is not None else None)
    def mary_mother_of_god(self, year=None):
        if year is None: year = self._year
        if self._mary_mother_of_god[year]:
            return self._mary_mother_of_god[year]
        self._mary_mother_of_god[year] = _date(year, 1, 1)
        return self._mary_mother_of_god[year]
    def annunciation(self, year=None):
        if year is None: year = self._year
        if self._annunciation[year]:
            return self._annunciation[year]
        date = _date(year, 3, 25)
        palm_sunday = self.palm_sunday(year)
        divine_mercy_sunday = self.divine_mercy_sunday(year)
        if date >= palm_sunday and date <= divine_mercy_sunday:
            date = (divine_mercy_sunday + timedelta(days=1))
        self._annunciation[year] = date
        return self._annunciation[year]
    def nativity_of_john_the_baptist(self, year=None):
        if year is None: year = self._year
        if self._nativity_of_john_the_baptist[year]:
            return self._nativity_of_john_the_baptist[year]
        self._nativity_of_john_the_baptist[year] = _date(year, 6, 24)
        return self._nativity_of_john_the_baptist[year]
    def peter_and_paul_apostles(self, year=None):
        if year is None: year = self._year
        if self._peter_and_paul_apostles[year]:
            return self._peter_and_paul_apostles[year]
        self._peter_and_paul_apostles[year] = _date(year, 6, 29)
        return self._peter_and_paul_apostles[year]
    def assumption(self, year=None):
        if year is None: year = self._year
        if self._assumption[year]:
            return self._assumption[year]
        self._assumption[year] = _date(year, 8, 15)
        return self._assumption[year]
    def all_saints(self, year=None):
        if year is None: year = self._year
        if self._all_saints[year]:
            return self._all_saints[year]
        self._all_saints[year] = _date(year, 11, 1)
        return self._all_saints[year]
    def immaculate_conception_of_mary(self, year=None):
        if year is None: year = (self._year - 1 if self._is_liturgical_year else self._year)
        if self._immaculate_conception_of_mary[year]:
            return self._immaculate_conception_of_mary[year]
        date = _date(year, 12, 8)
        if (date.weekday() + 1) % 7 == 0:
            date = (date + timedelta(days=1))
        self._immaculate_conception_of_mary[year] = date
        return self._immaculate_conception_of_mary[year]
    def ascension(self, year=None, ascension_on_sunday=None):
        if year is None: year = self._year
        if ascension_on_sunday is None: ascension_on_sunday = self._config.ascension_on_sunday
        id_ = str(year) + str(ascension_on_sunday)
        if self._ascension[id_]:
            return self._ascension[id_]
        self._ascension[id_] = ((self.easter_sunday(year) + timedelta(days=42)) if ascension_on_sunday else (self.easter_sunday(year) + timedelta(days=39)))
        return self._ascension[id_]
    def mary_mother_of_the_church(self, year=None):
        if year is None: year = self._year
        if self._mary_mother_of_the_church[year]:
            return self._mary_mother_of_the_church[year]
        self._mary_mother_of_the_church[year] = (self.easter_sunday(year) + timedelta(days=50))
        return self._mary_mother_of_the_church[year]
    def trinity_sunday(self, year=None):
        if year is None: year = self._year
        if self._trinity_sunday[year]:
            return self._trinity_sunday[year]
        self._trinity_sunday[year] = (self.easter_sunday(year) + timedelta(days=56))
        return self._trinity_sunday[year]
    def corpus_christi(self, year=None, corpus_christi_on_sunday=None):
        if year is None: year = self._year
        if corpus_christi_on_sunday is None: corpus_christi_on_sunday = self._config.corpus_christi_on_sunday
        id_ = str(year) + str(corpus_christi_on_sunday)
        if self._corpus_christi[id_]:
            return self._corpus_christi[id_]
        self._corpus_christi[id_] = ((self.easter_sunday(year) + timedelta(days=63)) if corpus_christi_on_sunday else (self.easter_sunday(year) + timedelta(days=60)))
        return self._corpus_christi[id_]
    def most_sacred_heart_of_jesus(self, year=None):
        if year is None: year = self._year
        if self._most_sacred_heart_of_jesus[year]:
            return self._most_sacred_heart_of_jesus[year]
        self._most_sacred_heart_of_jesus[year] = (self.easter_sunday(year) + timedelta(days=68))
        return self._most_sacred_heart_of_jesus[year]
    def immaculate_heart_of_mary(self, year=None):
        if year is None: year = self._year
        if self._immaculate_heart_of_mary[year]:
            return self._immaculate_heart_of_mary[year]
        self._immaculate_heart_of_mary[year] = (self.easter_sunday(year) + timedelta(days=69))
        return self._immaculate_heart_of_mary[year]
    def holy_family(self, year=None):
        if year is None: year = (self._year - 1 if self._is_liturgical_year else self._year)
        if self._holy_family[year]:
            return self._holy_family[year]
        self._holy_family[year] = (_date(year, 12, 30) if (self.christmas(year).weekday() + 1) % 7 == 0 else start_of_week((self.christmas(year) + timedelta(days=7))))
        return self._holy_family[year]
    def baptism_of_the_lord(self, year=None, epiphany_on_sunday=None):
        if year is None: year = self._year
        if epiphany_on_sunday is None: epiphany_on_sunday = self._config.epiphany_on_sunday
        id_ = str(year) + str(epiphany_on_sunday)
        if self._baptism_of_the_lord[id_]:
            return self._baptism_of_the_lord[id_]
        epiphany = self.epiphany(year, epiphany_on_sunday)
        if epiphany.day == 6:
            return start_of_week((epiphany + timedelta(days=7)))
        if ((epiphany.weekday() + 1) % 7 == 0 and epiphany.day == 7) or epiphany.day == 8:
            return (epiphany + timedelta(days=1))
        self._baptism_of_the_lord[id_] = start_of_week((epiphany + timedelta(days=7)))
        return self._baptism_of_the_lord[id_]
    def presentation_of_the_lord(self, year=None):
        if year is None: year = self._year
        if self._presentation_of_the_lord[year]:
            return self._presentation_of_the_lord[year]
        self._presentation_of_the_lord[year] = _date(year, 2, 2)
        return self._presentation_of_the_lord[year]
    def transfiguration(self, year=None):
        if year is None: year = self._year
        if self._transfiguration[year]:
            return self._transfiguration[year]
        self._transfiguration[year] = _date(year, 8, 6)
        return self._transfiguration[year]
    def exaltation_of_the_holy_cross(self, year=None):
        if year is None: year = self._year
        if self._exaltation_of_the_holy_cross[year]:
            return self._exaltation_of_the_holy_cross[year]
        self._exaltation_of_the_holy_cross[year] = _date(year, 9, 14)
        return self._exaltation_of_the_holy_cross[year]
    def lunar_new_year(self_or_utc_offset, _p1=None, _p2=None):
        if isinstance(self_or_utc_offset, Dates):
            self = self_or_utc_offset
            utc_offset = _p1
            year = _p2
            if year is None: year = self._year
            id_ = f"{utc_offset}:{year}"
            if self._lunar_new_year[id_]:
                return self._lunar_new_year[id_]
            self._lunar_new_year[id_] = Dates.lunar_new_year(utc_offset, year)
            return self._lunar_new_year[id_]
        else:
            utc_offset = self_or_utc_offset
            year = _p1
            _tmp_0 = calculate_lunar_new_year(year, utc_offset)
            day = _tmp_0.day
            month = _tmp_0.month
            return _date(year, month, day)
    def sunday_on_or_after_lunar_new_year(self_or_utc_offset, _p1=None, _p2=None):
        if isinstance(self_or_utc_offset, Dates):
            self = self_or_utc_offset
            utc_offset = _p1
            year = _p2
            if year is None: year = self._year
            id_ = f"{utc_offset}:{year}"
            if self._sunday_on_or_after_lunar_new_year[id_]:
                return self._sunday_on_or_after_lunar_new_year[id_]
            self._sunday_on_or_after_lunar_new_year[id_] = Dates.sunday_on_or_after_lunar_new_year(utc_offset, year)
            return self._sunday_on_or_after_lunar_new_year[id_]
        else:
            utc_offset = self_or_utc_offset
            year = _p1
            lny = Dates.lunar_new_year(utc_offset, year)
            day_of_week = (lny.weekday() + 1) % 7
            days_until_sunday = (7 - day_of_week) % 7
            return (lny + timedelta(days=days_until_sunday))
    def start_of_seasons(self, year=None):
        if year is None: year = self._year
        if self._start_of_seasons[year]:
            return self._start_of_seasons[year]
        self._start_of_seasons[year] = _Obj({"ADVENT": self.first_sunday_of_advent(year - 1), "CHRISTMAS_TIME": self.christmas(year - 1), "EASTER_TIME": self.easter_sunday(year), "LENT": self.ash_wednesday(year), "ORDINARY_TIME": (self.baptism_of_the_lord(year) + timedelta(days=1)), "PASCHAL_TRIDUUM": self.holy_thursday(year)})
        return self._start_of_seasons[year]
    def end_of_seasons(self, year=None):
        if year is None: year = self._year
        if self._end_of_seasons[year]:
            return self._end_of_seasons[year]
        self._end_of_seasons[year] = _Obj({"ADVENT": _date(year - 1, 12, 24), "CHRISTMAS_TIME": self.baptism_of_the_lord(year), "EASTER_TIME": self.pentecost_sunday(year), "LENT": self.holy_thursday(year), "ORDINARY_TIME": (self.christ_the_king_sunday(year) + timedelta(days=6)), "PASCHAL_TRIDUUM": self.easter_sunday(year)})
        return self._end_of_seasons[year]

