# AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
# Re-run the script to regenerate after updating the romcal TypeScript source.
# romcal version: 3.0.0-dev.125

"""
utils/easter.py — Python port of @internal/easter.

Gregorian Easter (Oudin/Seidelmann algorithm) and Julian Easter
(Meeus algorithm) converted to Gregorian calendar.

AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
"""

from __future__ import annotations
import math
from datetime import date as _date
from romcal.utils.objects import _Obj

GREGORIAN_EPOCH = 1721425.5

def calculate_gregorian_easter_date(year):
    Y = year
    C = int(Y // 100)
    N = Y - 19 * int(Y // 19)
    K = int((C - 17) // 25)
    I = C - int(C // 4) - int((C - K) // 3) + 19 * N + 15
    I -= 30 * int(I // 30)
    I -= int(I // 28) * (1 - int(I // 28) * int(29 // (I + 1)) * int((21 - N) // 11))
    J = Y + int(Y // 4) + I + 2 - C + int(C // 4)
    J -= 7 * int(J // 7)
    L = I - J
    M = 3 + int((L + 40) // 44)
    D = L + 28 - 31 * int(M // 4)
    return _Obj({"year": Y, "month": M, "day": D})

def mod(a, b):
    return a - b * int(a // b)

def is_leap_gregorian_year(year):
    return year % 4 == 0 and not (year % 100 == 0 and year % 400 != 0)

def leap_day(year, month):
    leap_offset = (-1 if is_leap_gregorian_year(year) else -2)
    return (0 if month <= 2 else leap_offset)

def gregorian_to_julian_day(year, month, day):
    return (GREGORIAN_EPOCH - 1 + 365 * (year - 1) + int((year - 1) // 4) + -int((year - 1) // 100) + int((year - 1) // 400) + int((367 * month - 362) / 12 + leap_day(year, month) + day))

def julian_to_julian_day(date):
    year = date.year
    month = (date.month - 1) + 1
    day = date.day
    if year < 1:
        year += 1
    if month <= 2:
        year -= 1
        month += 12
    return int(365.25 * (year + 4716)) + int(30.6001 * (month + 1)) + day - 1524.5

def julian_day_to_gregorian(julian_day):
    wjd = int(julian_day - 0.5) + 0.5
    depoch = wjd - GREGORIAN_EPOCH
    quadricent = int(depoch // 146097)
    dqc = mod(depoch, 146097)
    cent = int(dqc // 36524)
    dcent = mod(dqc, 36524)
    quad = int(dcent // 1461)
    dquad = mod(dcent, 1461)
    yindex = int(dquad // 365)
    year = quadricent * 400 + cent * 100 + quad * 4 + yindex
    if not (cent == 4 or yindex == 4):
        year += 1
    yearday = wjd - gregorian_to_julian_day(year, 1, 1)
    leapday_offset = (1 if is_leap_gregorian_year(year) else 2)
    leapadj = (0 if wjd < gregorian_to_julian_day(year, 3, 1) else leapday_offset)
    month = int(((yearday + leapadj) * 12 + 373) // 367)
    day = wjd - gregorian_to_julian_day(year, month, 1) + 1
    return _date(int(year), int((month - 1) + 1), int(day))

def julian_to_gregorian(date):
    return julian_day_to_gregorian(julian_to_julian_day(date))

def calculate_julian_easter_date(year):
    a = year % 4
    b = year % 7
    c = year % 19
    d = (19 * c + 15) % 30
    e = (2 * a + 4 * b - d + 34) % 7
    month = int((d + e + 114) // 31)
    day = ((d + e + 114) % 31) + 1
    return _date(int(year), int((month - 1) + 1), int(day))

def calculate_julian_easter_date_to_gregorian_date(year):
    if year < 326:
        raise RuntimeError("Easter date calculation within the Julian calendar is not valid for years before 326 AD")
    date = julian_to_gregorian(calculate_julian_easter_date(year))
    return _Obj({"year": date.year, "month": (date.month - 1) + 1, "day": date.day})

