# AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
# Re-run the script to regenerate after updating the romcal TypeScript source.
# romcal version: 3.0.0-dev.125

"""
utils/lunar_new_year.py — Python port of @internal/lunar-new-year.

Lunar New Year date computation based on Jean Meeus,
"Astronomical Algorithms", Willmann-Bell, 1991.

AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
"""

from __future__ import annotations
import math
from romcal.utils.objects import _Obj

sin = lambda degrees: math.sin((degrees * math.pi) / 180)

cos = lambda degrees: math.cos((degrees * math.pi) / 180)

def jde_to_julian_day_number(jde, utc_offset):
    return int(jde + utc_offset / 24 + 0.5)

def jde_to_date(jde, utc_offset):
    adjusted_jde = jde + utc_offset / 24
    z = int(adjusted_jde + 0.5)
    A = None
    if z < 2299161:
        A = z
    else:
        alpha = int((z - 1867216.25) // 36524.25)
        A = z + 1 + alpha - int(alpha // 4)
    B = A + 1524
    C = int((B - 122.1) // 365.25)
    D = int(365.25 * C)
    E = int((B - D) // 30.6001)
    day = B - D - int(30.6001 * E)
    month = (E - 1 if E < 14 else E - 13)
    year = (C - 4716 if month > 2 else C - 4715)
    return _Obj({"year": year, "month": month, "day": day})

def winter_solstice_jde(year):
    Y = (year - 2000) / 1000
    JDE0 = 2451900.05952 + 365242.74049 * Y - 0.06223 * Y * Y - 0.00823 * Y * Y * Y + 0.00032 * Y * Y * Y * Y
    T = (JDE0 - 2451545.0) / 36525
    S = 485 * cos(324.96 + 1934.136 * T) + 203 * cos(337.23 + 32964.467 * T) + 199 * cos(342.08 + 20.186 * T) + 182 * cos(27.85 + 445267.112 * T) + 156 * cos(73.14 + 45036.886 * T) + 136 * cos(171.52 + 22518.443 * T) + 77 * cos(222.54 + 65928.934 * T) + 74 * cos(296.72 + 3034.906 * T) + 70 * cos(243.58 + 9037.513 * T) + 58 * cos(119.81 + 33718.147 * T) + 52 * cos(297.17 + 150.678 * T) + 50 * cos(21.02 + 2281.226 * T) + 45 * cos(247.54 + 29929.562 * T) + 44 * cos(325.15 + 31555.956 * T) + 29 * cos(60.93 + 4443.417 * T) + 18 * cos(155.12 + 67555.328 * T) + 17 * cos(288.79 + 4562.452 * T) + 16 * cos(198.04 + 62894.029 * T) + 14 * cos(199.76 + 31436.921 * T) + 12 * cos(95.39 + 14577.848 * T) + 12 * cos(287.11 + 31931.756 * T) + 12 * cos(320.81 + 34777.259 * T) + 9 * cos(227.73 + 1222.114 * T) + 8 * cos(15.45 + 16859.074 * T)
    return JDE0 + S * 0.00001

def new_moon_jde(k):
    T = k / 1236.85
    T2 = T * T
    T3 = T2 * T
    T4 = T3 * T
    JDE = 2451550.09766 + 29.530588861 * k + 0.00015437 * T2 - 0.00000015 * T3 + 0.00000000073 * T4
    E = 1 - 0.002516 * T - 0.0000074 * T2
    M = 2.5534 + 29.1053567 * k - 0.0000014 * T2 - 0.00000011 * T3
    Mp = 201.5643 + 385.81693528 * k + 0.0107582 * T2 + 0.00001238 * T3 - 0.000000058 * T4
    F = 160.7108 + 390.67050284 * k - 0.0016118 * T2 - 0.00000227 * T3 + 0.000000011 * T4
    Omega = 124.7746 - 1.56375588 * k + 0.0020672 * T2 + 0.00000215 * T3
    correction = -0.4072 * sin(Mp) + 0.17241 * E * sin(M) + 0.01608 * sin(2 * Mp) + 0.01039 * sin(2 * F) + 0.00739 * E * sin(Mp - M) + -0.00514 * E * sin(Mp + M) + 0.00208 * E * E * sin(2 * M) + -0.00111 * sin(Mp - 2 * F) + -0.00057 * sin(Mp + 2 * F) + 0.00056 * E * sin(2 * Mp + M) + -0.00042 * sin(3 * Mp) + 0.00042 * E * sin(M + 2 * F) + 0.00038 * E * sin(M - 2 * F) + -0.00024 * E * sin(2 * Mp - M) + -0.00017 * sin(Omega) + -0.00007 * sin(Mp + 2 * M) + 0.00004 * sin(2 * Mp - 2 * F) + 0.00004 * sin(3 * M) + 0.00003 * sin(Mp + M - 2 * F) + 0.00003 * sin(2 * Mp + 2 * F) + -0.00003 * sin(Mp + M + 2 * F) + 0.00003 * sin(Mp - M + 2 * F) + -0.00002 * sin(Mp - M - 2 * F) + -0.00002 * sin(3 * Mp + M) + 0.00002 * sin(4 * Mp)
    JDE += correction
    A1 = 299.77 + 132.8475848 * k - 0.009173 * T2
    A2 = 251.88 + 92.517136 * k
    A3 = 251.83 + 360.58068 * k
    A4 = 349.42 + 450.37168 * k
    A5 = 84.66 + 966.20036 * k
    A6 = 141.74 + 1361.55178 * k
    A7 = 207.14 + 1759.87848 * k
    A8 = 154.84 + 7.30686 * k
    A9 = 34.52 + 27.261239 * k
    A10 = 207.19 + 1154.8622 * k
    A11 = 291.34 + 0.09133 * k
    A12 = 161.72 + 31.85958 * k
    A13 = 239.56 + 25.13124 * k
    A14 = 331.55 + 481.75148 * k
    JDE += 0.000325 * sin(A1) + 0.000165 * sin(A2) + 0.000164 * sin(A3) + 0.000126 * sin(A4) + 0.00011 * sin(A5) + 0.000062 * sin(A6) + 0.00006 * sin(A7) + 0.000056 * sin(A8) + 0.000047 * sin(A9) + 0.000042 * sin(A10) + 0.00004 * sin(A11) + 0.000037 * sin(A12) + 0.000035 * sin(A13) + 0.000023 * sin(A14)
    return JDE

def calculate_lunar_new_year(year, utc_offset):
    solstice_jde = winter_solstice_jde(year - 1)
    solstice_day = jde_to_julian_day_number(solstice_jde, utc_offset)
    decimal_year = year - 1 + 11.5 / 12
    k = int((decimal_year - 2000) * 12.3685)
    while jde_to_julian_day_number(new_moon_jde(k + 1), utc_offset) <= solstice_day:
        k += 1
    lny_jde = new_moon_jde(k + 2)
    return jde_to_date(lny_jde, utc_offset)

