# AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
# Re-run the script to regenerate after updating the romcal TypeScript source.
# romcal version: 3.0.0-dev.125

"""
utils/numbers.py — Python port of romcal utils/numbers.ts.

AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
"""

from __future__ import annotations

from romcal.utils.objects import _Obj

numerals = _Obj({"M": 1000, "CM": 900, "D": 500, "CD": 400, "C": 100, "XC": 90, "L": 50, "XL": 40, "X": 10, "IX": 9, "V": 5, "IV": 4, "I": 1})

def to_roman_number(number):
    keys = list(numerals.keys())
    arabic = number
    roman_str = ""
    for i in range(len(keys)):
        key = keys[i]
        roman_str += (key * int((arabic / numerals[key])))
        arabic %= numerals[key]
    return roman_str

is_integer = lambda value: isinstance(value, (int, float)) and isinstance(value, int)

