# AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
# Re-run the script to regenerate after updating the romcal TypeScript source.
# romcal version: 3.0.0-dev.125

"""
utils/string.py — Python port of romcal utils/string.ts.

AUTO-GENERATED by scripts/translate_calendar.py. DO NOT EDIT BY HAND.
"""

from __future__ import annotations

import re

to_screaming_snake_case = lambda string: re.sub(r"(^_*|_*$)", "", re.sub(r"[ \t\n]+_*", "_", re.sub(r"[A-Z]", lambda _m: f"_{_m.group(0).lower()}", string))).upper()

def to_package_name(string, prefix=False):
    package_name = re.sub(r"_", ".", re.sub(r"([a-z0-9]|^)([A-Z])", lambda _m: ((f"{_m.group(1)}-{_m.group(2)}" if _m.group(1) else _m.group(2))), string), count=1).lower()
    return (f"@romcal/calendar.{package_name}" if prefix else package_name)

to_camel_case = lambda string: re.sub(r"((?:-|_|\s)\w)", lambda _m: _m.group(0)[1].upper(), string.lower())

capitalize = lambda string: string[0].upper() + string[1:]

to_pascal_case = lambda string: capitalize(re.sub(r"((?:-|_|\s)\w)", lambda _m: _m.group(0)[1].upper(), string.lower()))

un_capitalize = lambda string: string[0].lower() + re.sub(r"(_[A-Z]+)", lambda _m: _m.group(0).lower(), string[1:])

def sanitize_locale_id(locale_id):
    if len(locale_id) >= 5:
        return f"{locale_id[0:2].lower()}-{locale_id[3:5].upper()}"
    return locale_id.lower()

